README.md
src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Types/DocumentSignatureSentType.php
src/graphql/documentSignatureSent.graphql

- User should be able to see parent data from the detail page document signature sent request sign
- If the `parent` is `not null` & `status = 0`, the user `can not sign` the document
- If the `parent` is `not null` & `status = 4`, the user `can not sign` the document
- If the `parent` is `not null` & `status = 1`, the user will be `allowed to sign` the document
- If the `parent` `is null`, the user will be `allowed to sign` the document
Related Task : https://sharing.clickup.com/t/h/1rx6hcb/70W8POC6Y1JJKXL
- Add parent type on `DocumentSignatureSentType`
````
{
documentSignatureSent(id: $id) {
id
...
...
parent {
id
status
sort
receiver {
name
}
}
...
...
...
}
}
````
title: Menambahkan type parent untuk validasi user dapat melakukan tte
project: SIKD …

Create parent type on document signature sent type

---

src/app/GraphQL/Queries/InboxQuery.php
src/graphql/inbox.graphql
src/graphql/schema.graphql

- Add unread inbox counting functionality
- The counters are scoped by REGIONAL and INTERNAL inbox
```
{
inboxUnreadCount{
regional
internal
}
}
```
__
title: Add unread inbox couting
project: SIKD

Add unread inbox couting

---

src/app/Models/InboxReceiver.php
src/app/Models/InboxReceiverCorrection.php
src/graphql/inboxReceiver.graphql
src/graphql/inboxReceiverCorrection.graphql
src/graphql/schema.graphql

- Add `InboxReceiverCorrection` model to acomodate the drafts list
- Add grouping filter for grouping the drafts list by its `NId` and gets the latest as the result
```
{
drafts(
first: 10
grouping: true
){
pageInfo{
total
}
edges{
node{
sender{
name
}
receiver{
name
}
draftDetail{
id
date
receiverAs
number
letterNumber
about
moreAbout
location
address
folder
type{
id
name
}
urgency{
id
name
}
createdBy{
id
name
}
reviewer{
id
name
}
}
draftId
groupId
date
fromId
toId
message
receiverAs
receiveStatus
toIdDesc
isActioned
correctionId
}
}
}
}
```
__
title: Add Drafts List from Inbox Receiver Correction Table
project: SIKD

Add Drafts List from Inbox Receiver Correction Table

---

src/app/GraphQL/Queries/DraftQuery.php
src/app/GraphQL/Queries/InboxQuery.php
src/graphql/schema.graphql

- User should be able to see a detailed draft
- Add `DraftQuery` to handle change read status
````
{
draft(
draftId: $draftId,
groupId: $groupId,
){
sender{
name
}
receiver{
id
name
}
draftId
groupId
date
fromId
toId
message
receiverAs
receiveStatus
toIdDesc
isActioned
correctionId
draftDetail {
about
}
}
}
````
title: User dapat melihat detail konsep naskah
project: SIKD

User should be able to see detail draft

---

src/app/GraphQL/Queries/DraftQuery.php
src/app/Models/InboxReceiverCorrection.php
src/graphql/inboxReceiverCorrection.graphql
src/graphql/schema.graphql

- User should be able to see people timeline draft
- Add `DraftQuery@timeline` to see people timeline using `DraftTimelineInput`
- Add `TimelineType` for set type at `DraftTimelineInput`
- `TimelineType` for now have value `VERIFICATION` (koreksi), for get people who's correction the draft
````
{
draftTimeline(
filter: {
draftId: "$id",
type: CORRECTION
}
){
sender{
name
}
receiver{
id
name
}
draftId
groupId
date
fromId
toId
message
receiverAs
receiveStatus
toIdDesc
isActioned
correctionId
draftDetail {
about
}
}
}
````
title: User dapat melihat detail konsep naskah
project: SIKD

User should be able to see people timeline draft

---

src/app/Enums/SignatureStatusTypeEnum.php
src/app/Models/DocumentSignatureSent.php
src/graphql/documentSignatureSent.graphql

- User should be able to see grouping timeline people by unsigned and signed
- Modify enum value `StatusType` to `SIGNED` and `UNSIGNED`
- Add enum value `SIGNED` and `UNSIGNED` at `SignatureStatusTypeEnum.php`
````
{
documentSignatureSentTimeline(
filter: {
documentSignatureId:  $documentSignatureId,
sort: "3"
status: SIGNED
}
) {
id
....
}
````
title: Membuat grouping user timeline berdasarkan yang sudah & belum tandatangan dokumen
project: SIKD

Enhance grouping timeline user by unsigned and signed

---

src/app/Models/DocumentSignature.php
src/app/Models/InboxFile.php
src/graphql/documentSignature.graphql
src/graphql/inboxFile.graphql

- User should be able to see the sender and receiver after the document attached in the inbox feature (pencatatan naskah keluar)
- Add relation between `DocumentSignature` and `InboxFile`
- Add relation between `InboxFile` and `InboxReceiver`
The existing code didn't have a foreign key from `InboxFile` with `DocumentSignature`, so I found field `FileName_real` from `InboxFile` can be relational with `DocumentSignature` field `file`
````
{
documentSignature(id: $documentSignatureId) {
id
name
url
inboxFile {
inboxReceiver {
sender {
name
avatar {
url
}
role {
name
}
}
receiver {
name
avatar {
url
}
role {
name
}
}
}
}
documentSignatureSents {
id
signatureId
peopleId
to
date
note
status
...
}
}
}
````
title: Add document signature relation with inbox
project: SIKD
participants: …

Add document signature relation with inbox

---

src/app/Models/InboxFile.php
src/graphql/inboxFile.graphql

- User should be able to see the sender and **receivers/multiple receiver** after the document attached in the inbox feature (pencatatan naskah keluar)
- Add relation between `InboxFile` and `InboxReceiver` (**one to many**)
- change from `inboxReceiver` to `inboxReceivers`
````
{
documentSignature(id: $documentSignatureId) {
id
name
url
inboxFile {
inboxReceivers {
sender {
name
avatar {
url
}
role {
name
}
}
receiver {
name
avatar {
url
}
role {
name
}
}
}
}
documentSignatureSents {
id
signatureId
peopleId
to
date
note
status
...
}
}
}
````
title: Change document signature relation (one to many) with inbox
project: SIKD

Change relation inbox receiver from belongsTo to hasMany

---

src/app/GraphQL/Queries/InboxQuery.php
src/config/constants.php

- Add array constants named `peoplePositionGroups`
- This constants contains user positions groups classifications
- Each groups have different unread inbox behavior
- For groups 2 and 9 have the same counter method called `unreadCounterDeptQuery`
__
title: Add unread inbox counter for positions group 2 and 9
project: SIKD

Add unread inbox counter for 'Kadis/Sekdis' roles

---

src/app/Models/InboxReceiverCorrection.php

Modify the `InboxReceiverCorrection` table primary key from `NId` to `Id`.
This modification regarding to the `InboxReceiverCorrection` table structure changes.
__
title: Modify inbox receiver correction primary key
project: SIKD

Modify inbox receiver correction primary key

---

src/app/GraphQL/Queries/DraftQuery.php
src/app/Models/InboxReceiverCorrection.php
src/graphql/inboxReceiverCorrection.graphql

- User should be able to see the timeline draft document before the signed document
- Change query on `DraftQuery.php` add `whereIn` first draft (`to_draft_*`) and forward (`meneruskan`)
title: Menyesuaikan query draft timeline pada konsep nasak\ah dokumen sebelum ditandatangani
project: SIKD

Adjust draft timeline response with to_draft_* & forward status

---

src/app/GraphQL/Queries/InboxQuery.php

- Modify the query, to check if the sender is from the same department with the user
- Checking is the inbox from `eksternal` source
__
title: Bugfix unread regional inbox counter
project: SIKD

Bugfix unread regional inbox counter

---

src/app/Models/InboxReceiverCorrection.php

Change the query regarding into the business process definition.
The `receiverReviewQuery` query will cost more than 500 ms in response. This issue caused by the existing db structures does not accommodate the wanted feature (drafts filter). Therefore, the complex query is forced to support.
This time response issue will be fixed when the existing team already modified their db structures.
__
title: Modify receiver types filtering query
project: SIKD

Modify receiver types filtering query

---

src/app/GraphQL/Mutations/InboxMutator.php
src/app/Models/InboxReceiver.php
src/graphql/inboxReceiver.graphql
src/graphql/schema.graphql

- User should be able to see the status `isFollowUp` when the inbox is already actioned
- Adjust inbox mutator for fill `TindakLanjut` field
- Add `isFollowUp` for flagging data is already actioned
````
{
inboxHistory(
inboxId: "218051121112809",
first: 10
) {
edges {
node {
id
inboxId
fromId
toId
isForwarded
isFollowUp
isEndForward
}
}
}
}
````
title: User dapat melihat flag surat telah ditindaklanjuti pada history naskah
project: SIKD

Add isFollowUp on inbox history

---

src/app/GraphQL/Mutations/InboxReceiverCorrectionMutator.php
src/app/Models/InboxCorrection.php
src/app/Models/InboxReceiverCorrection.php
src/app/Models/MasterCorrectionOption.php
src/graphql/inboxReceiverCorrection.graphql
src/graphql/masterCorrectionOption.graphql
src/graphql/schema.graphql

- Add `masterCorrectionOptions` query to show the data from `master_koreksi` table
- Add `draftReturn` mutation to rerturn the draft to the drafter
- `masterCorrectionOptions` query
```
{
correctionOptions(first:10){
edges{
node{
id
name
}
}
}
}
```
- `draftReturn` mutation
```
mutation{
draftReturn(input: {
id: 3432
options: "XxJyPn38Yh.1, XxJyPn38Yh.10, XxJyPn38Yh.2"
drafterId: 218
message: "tolong diperbaiki"
}){
id
draftId
groupId
date
fromId
toId
message
draftDetail{
receiverAs
}
}
}
```
__
title: Add returning back draft to the drafter feature
project: SIKD

Add returning back draft to the drafter feature

---

src/app/GraphQL/Queries/DocumentSignatureQuery.php
src/app/Models/DocumentSignatureSent.php
src/database/migrations/2021_12_17_024429_add_column_people_id_document_signature_sent_reads_table.php

- User should be able to see the flag read/unread document signature sent
- Add people id on `document_signature_sent_reads` for flagging by user
title: Menambahkan field people id pada flagging document signature sent read
project: SIKD

Add people id on document signature sent read

---

src/app/GraphQL/Queries/DraftQuery.php

- Add first data on inbox receiver correction for draft timeline
title: Add first data on inbox receiver correction for draft timeline
project: SIKD

Add first data on inbox receiver correction for draft timeline

---

src/app/Http/Traits/InboxFilterTrait.php

- Modify the filter condition to catch the `null` status 
title: Modify filter by forward status condition
project: SIKD

Modify filter by forward status condition

---

src/resources/views/pdf/layouts/attachment/attachment_array.blade.php
src/resources/views/pdf/layouts/master.blade.php
src/resources/views/pdf/nota_dinas.blade.php

- Fix attachment if data was an array on a pdf report
title: Fix attachment if data was an array on a pdf report
project: SIKD

Fix attachment if data was an array on a pdf report

---

src/app/Models/InboxReceiverCorrection.php
src/graphql/schema.graphql

- Create query draft history
````
query {
draftHistory(
draftId: $draftId
) {
id
draftId
groupId
date
fromId
toId
message
receiverAs
receiveStatus
sender {
id
name
}
receiver {
id
name
}
isActioned
draftDetail {
letterNumber
}
senderRequestSignature {
id
name
}
...
}
}
````
title: Create query draft history
project: SIKD

Create query draft history

---

src/app/GraphQL/Types/InboxReceiverCorrectionType.php

- Add optional condition when draft detail letter number is null
title: Add optional condition when draft detail letter number is null
project: SIKD
participants: @indraprasetya154 @samudra-ajri @ayocodingit @rizkyrmsyah @sandisunandar99 @rindibudiaramdhan

Add optional condition when draft detail letter number is null

---

.github/workflows/release-staging.yml

- Add `lighthouse:cache` on GitHub workflow for deployment purpose
- https://lighthouse-php.com/master/performance/schema-caching.html
title: Add `lighthouse:cache` on GitHub workflow for deployment purpose
project: SIKD
participants: @indraprasetya154 @samudra-ajri @yohang88

Add lighthouse:cache on github workflow

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Http/Traits/DraftTrait.php

- Fix validation header pdf image with `getimagesize`
- Fix `notadinas` bcc to inbox receiver after signed
title: Fix invalid output after signature the document nota dinas type
project: SIKD

Fix invalid output after signature the document nota dinas type

---

src/app/GraphQL/Mutations/InboxMutator.php

Modify the `or` into `and` condition for ignoring notification for numbering action. 
title: Modify the numbering temp condition
project: SIKD

Modify the numbering temp condition

---

src/app/Models/InboxReceiverCorrection.php

Hide activity correction by the drafter on draft history
title: Hide activity correction by the drafter on draft history
project: SIKD

Hide activity correction by the drafter on draft history

---

src/app/Models/DocumentSignatureSent.php
src/app/Models/DocumentSignatureSentRead.php
src/composer.json
src/composer.lock

Fix read status on document signature sent history
Eloquent doesn't support composite keys. As a consequence, there is no way to define a relationship from one model to another by matching more than one column. Trying to use where clauses (like in the example below) won't work when eager loading the relationship because at the time the relationship is processed $this->team_id is null.
Use this package: https://github.com/topclaudy/compoships
title: Fix read status on document signature sent history
project: SIKD

Fix read status on document signature sent history

---

src/app/GraphQL/Mutations/DocumentSignatureForwardMutator.php
src/app/Models/DocumentSignature.php
src/app/Models/DocumentSignatureType.php
src/graphql/documentSignature.graphql

- Now we don't need to choose UK/TU first on a mobile screen, because we have document type for sending the document to UK/TU
- Enhance documentSignatureForward receiver document
Frontend (mobile) need change paramters from:
````
docuumentSignatureId
sender
receiver
note
````
to:
````
documentSignatureSentId
note
````
https://app.clickup.com/t/2nc67v5
Enhance documentSignatureForward receiver document
project: SIKD

Enhance documentSignatureForward receiver document

---

src/app/Models/DocumentSignatureSent.php
src/graphql/documentSignatureSent.graphql
src/graphql/schema.graphql

- Add outbox signature sent searching feature 
- Add filtering by statuses
````
outboxDocumentSignatureSents(
first: 20
search: "...."
filter: {
statuses: "0, 1, 4" 
}
) {
edges {
node {
....
}
}
}
````
title: Add outbox signature searching and filtering
project: SIKD

Add outbox signature searching and filtering

---

src/app/Enums/ObjectiveTypeEnum.php
src/app/Models/DocumentSignatureSent.php
src/app/Models/InboxReceiverCorrection.php
src/graphql/documentSignatureSent.graphql
src/graphql/schema.graphql

- These objectives can be valued by `IN` or `OUT`
- `objective=IN` will filter the inbox signatures list that user received
- `objective=OUT` will filter the inbox signatures list that user sent
title: Add outbox signature objectives
project: SIKD

Add outbox signature objectives

---

src/app/GraphQL/Queries/InboxQuery.php

- This modification regards to the new inbox list receiverAs attribute addtioned
- It was `receiverAs=bcc`
title: Modify regional inbox unread counter
project: SIKD

Modify regional inbox unread counter

---

src/app/Models/InboxReceiverCorrection.php

- This modification according to the new implementation of `action_label`
- The filter only returns the records that already implemented this label
- It means the record where the `action_label` is not null
title: Modify the outbox drafts filter
project: SIKD

Modify the outbox drafts filter

---

src/app/Enums/InboxReceiverScopeType.php
src/app/GraphQL/Queries/InboxQuery.php

- Add `REGIONAL_DISPOSITION` enum
- Modify `DISPOSITION` enum into `INTERNAL_DISPOSITION`
- Modify the unread regional count value as the accumulation of forward and regional disposition count
title: Add regional disposition inbox receiver scope
project: SIKD

Add regional disposition inbox receiver scope

---

src/resources/views/pdf/surat_rekomendasi.blade.php

- Fix title split on next page letter recommendation pdf template
- https://app.clickup.com/t/2g50rhx
title: Fix title split on next page letter recommendation pdf template
project: SIKD

Fix title split on next page letter recommendation pdf template

---

src/app/Enums/CustomReceiverTypeEnum.php
src/app/Models/InboxReceiverCorrection.php

- Add DISTRIBUTION custom receiver type enum
- This filter will return the letters which has `SURAT DINAS` type and the receiver is `Unit Kearsipan`
- The filter cannot using multiple values
- The client (mobile) should use this query:
```
{
outboxDrafts(
filter: {
receiverTypes: "distribution"
}
)
}
```
title: Add distribution draft filter
project: SIKD

Add distribution draft filter

---

src/graphql/schema.graphql

- Add the inbox of external drafts list
- External draft is a letter that drafted outside sikd
- The client (mobile) should use this query:
```
{
externalDrafts(first: 50){
....
}
}
```
title: Add inbox external drafts list
project: SIKD

Add inbox external drafts list

---

src/graphql/documentSignatureForward.graphql

Add `isRead` attribute on `DoucmentSignatureForward` gql schema.
title: Add isRead attribute on Signature Forward schema
project: SIKD

Add isRead attribute on Signature Forward schema

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DocumentSignatureRejectMutator.php

- When a document is rejected the read status on the sender is false
- Similar thing when the document is signatured
title: Modify the read status after signature response
project: SIKD

Modify the read status after signature response

---

src/app/GraphQL/Types/DocumentSignatureSentType.php
src/graphql/documentSignatureSent.graphql

The `statusRead` is used for the read/unread label on the signature list, different from the history list that used `isRead` label.
The client (mobile) should change the attribute from `isRead` into `statusRead` in the query.
title: Add status read resolver
project: SIKD

Add status read resolver

---

src/app/Http/Traits/SendNotificationTrait.php

This function will handle the records that have no draft detail object.
title: Add optional function to the draft detail object
project: SIKD

Add optional function to the draft detail object

---

src/app/GraphQL/Mutations/DistributeDocumentMutator.php
src/app/GraphQL/Queries/DocumentSignatureHistoryQuery.php
src/graphql/documentSignatureSent.graphql

- Add document signature distribute at document signature history
- Change **status** `documentSignatureForward` to `1` after **distributed**
- https://app.clickup.com/t/2jfbvq2
Since documnet **already distributed** and **recorded** on `inbox_receiver table`
Attribute `documentSignatureDistribute` has type `InboxReceiver` structrure
````
{ 
documentSignatureSentHistory(documentSignatureId : "123456789") {
documentSignatureDistribute{
sender{
name
position
}
receiver{
name
position
}
}
documentSignatureForward{
date
status
note
sender{
name
position
}
receiver{
name
position
}
}
documentSignatureSent{
date
status
note
sender{
name
position
}
receiver{
name
position
}
read
id
sort
}
}
}
````
title: Add document signature distribute at document signature history
project: SIKD
participants: …

Add document signature distribute at document signature history

---

src/app/Models/Draft.php
src/graphql/schema.graphql

- Reverts jabardigitalservice/office-services#331
- This function cannot accomated the distributed list
- This revert because this feature already accomodate by `Drafts` query
This feature can be accomodate by this query:
```
{
drafts(
objective: IN
first: 20
filter: {
receiverTypes: "Meminta Nomber Surat, meneruskan"
}
){
...
}
}
```
title: Revert "Add internal drafts list for UK/TU"
project: SIKD

Revert "Add internal drafts list for UK/TU"

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- Remove rename file on first order if the document has a footer
title: Remove rename file on first order if the document has a footer
project: SIKD

Remove rename file on first order if the document has a footer

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/GraphQL/Queries/DraftHistoryQuery.php
src/config/constants.php

- Change response of inbox receiver attribute in draft history
- Change rule of forwarding draft after e-sign
title: Change response of inbox receiver attribute in draft history
project: SIKD

Change response of inbox receiver attribute in draft history

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Set const draftReceiverAsToTarget above forward inbox receiver
title: Set const draftReceiverAsToTarget above forward inbox receiver
project: SIKD

Set const draftReceiverAsToTarget above forward inbox receiver

---

src/app/Models/InboxReceiver.php
src/graphql/inboxReceiver.graphql

- Add exclude filter on inbox history
- Add `excludeStatus:  "bcc"` params on inboxHistory when user hit from detail inbox
````
inboxHistory(
filter: {
inboxId : "123123123123123123123" //sample inboxId
withAuthCheck : true
excludeStatus: "bcc"
} 
first: 10
){
...
...
...
}
}
````
`excludeStatus` can be used with any `ReceiverAs` value
title: Add exclude filter on inbox history
project: SIKD

Add exclude filter on inbox history

---

src/app/GraphQL/Queries/DocumentSignatureHistoryQuery.php
src/graphql/documentSignature.graphql
src/graphql/documentSignatureSent.graphql

- Set documentSignatureSelf on document signature history
- Use attribute `documentSignatureSelf` (check documentation first for see response)
````
{ 
documentSignatureSentHistory(documentSignatureId : "1234567689"){ //sample
documentSignatureDistribute{
....  
}
documentSignatureForward{
....
}
documentSignatureSent{
...
}
documentSignatureSelf {
id
createdBy {
name
}
createdAt //use it when updatedAt is null
updatedAt //use it when data not null
}
}
}
````
- https://gitlab.com/jdsteam/sikd-website/-/merge_requests/189
title: Set documentSignatureSelf on document signature history
project: SIKD

Set documentSignatureSelf on document signature history

---

src/app/Http/Traits/InboxFilterTrait.php

Bugfix the `whereHas` query to not use receiver, sender instead.
title: Modify "semua naskah" from UK
project: SIKD

Modify "semua naskah" from UK

---

src/app/Models/People.php

- This order query will overtake the lighthouse `orderBy` directive.
- This takeovering is needed reagards to the users have same roleId possibility.
title: Add disposition proposed people list underictive ordering
project: SIKD

Add disposition proposed people list underictive ordering

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Ignore TU Role from forwarding document notadinas group after esign
title: Ignore TU Role from forwarding document notadinas group after esign
project: SIKD

Ignore TU Role from forwarding document notadinas group after esign

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Add notification to target after draft esign
- https://app.clickup.com/t/2a1q8fh
title: Add notification to target after draft esign
project: SIKD

Add notification to target after draft esign

---

src/app/Enums/InboxTypeEnum.php
src/app/Models/InboxReceiver.php

- Add condition label 'to' on inbox history when the draft is non disposition
- https://app.clickup.com/t/25cwf58?comment=804690660
title: Add condition label 'to' on inbox history when the draft is non disposition
project: SIKD

Add condition label to on inbox history when draft is non disposition

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Re set group id on forwarding document (notification) after esign
- https://app.clickup.com/t/2a1q8fh?comment=810877329
title: Re set group id on forwarding document (notification) after esign
project: SIKD

Re set group id on forward notification after esign

---

src/app/Models/DocumentSignatureSent.php
src/graphql/documentSignatureSent.graphql

- Add previous attribute on document signature sent response
- https://app.clickup.com/t/2d8fy18
- Use previous attribute to get people name
title: Add previous attribute on document signature sent response
project: SIKD

Add previous attribute on document signature sent response

---

src/app/Models/DocumentSignature.php
src/graphql/documentSignature.graphql
src/graphql/documentSignatureSent.graphql

- Add attachment attribute on document signature response
- https://app.clickup.com/t/2d31ua6
````
{
documentSignatureSent(id: "XXX") {
id
documentSignature {
id
url
attachment
note
}
read
note
sender {
name
}
receiver {
name
}
previous {
name
}
}
}
````
title: Add attachment attribute on document signature response
project: SIKD

Add attachment attribute on document signature response

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Enhance change link of qrcode esign
- Camera can't scan qrcode image (the main problem qrcode has an image in front of it)
- https://app.clickup.com/t/2d311at?comment=834757506
- https://gitlab.com/jdsteam/sikd-website/-/merge_requests/236
title: Add attachment attribute on document signature response
project: SIKD

Enhance change link of qrcode esign

---

src/app/GraphQL/Mutations/DocumentSignatureRejectMutator.php
src/app/Models/DocumentSignatureSent.php
src/graphql/documentSignatureSent.graphql

- Add forward people id on document esign response
- Change forward people on reject document esign
- https://app.clickup.com/t/2d8fy18
- Migration and changes on website https://gitlab.com/jdsteam/sikd-website/-/merge_requests/248
title: Set param on forward receiver after esign by drafter role
project: SIKD

Add forward people id on document esign response

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- Set forward target people id for gubernur and wakil gubernur role after last people esign
- https://app.clickup.com/t/2dtxv8x
title: Set forward target people id for gubernur and wakil gubernur role after last people esign
project: SIKD

Set forward target people id for gubernur and wakil gubernur role after last people esign

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/Models/DocumentSignature.php
src/graphql/documentSignature.graphql

- [Create `canDownload` attribute for flagging download button at clients](https://github.com/jabardigitalservice/office-services/commit/e4564b8613bf83f0cb4c796389299b37ae56f48a)
- Remove unused flow code (for check parent)
````
{
documentSignatureSent(id: "xxx") {
id
documentSignature {
id
url
canDownload
attachment
note
}
read
next
note
sender {
name
}
receiver {
name
}
previous {
name
}
forward {
name
}
}
}
````
- https://app.clickup.com/t/2h6e9xx
title: Create canDownload attribute for flagging download button at clients
project: SIKD

Create canDownload attribute for flagging download button at clients

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php

- fix: change file upload esign method from pdf byte to upload new file
title: fix: change file upload esign method from pdf byte to upload new file
project: SIKD

fix: change file upload esign method from pdf byte to upload new file

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php

- fix: Change fopen to file_get_contents on upload footer file esign
title: fix: Change fopen to file_get_contents on upload footer file esign
project: SIKD

Change fopen to file_get_contents on upload footer file esign

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- fix: Rollback tmp file upload pdf footer for esign
- Rollback from this : 
- https://github.com/jabardigitalservice/office-services/pull/442
- https://github.com/jabardigitalservice/office-services/pull/443
title: fix: Rollback tmp file upload pdf footer for esign
project: SIKD
participants: @indraprasetya154 @samudra-ajri @fajarhikmal214 @ayocodingit

fix: Rollback tmp file upload pdf footer for esign

---

src/app/Models/InboxReceiver.php

- This modification will rsults the filter with the word prefix.
-  For example, we have a sentence: 'The coconut export trend', then the input search keyword is 'expo'.
- With `NATURAL LANGUAGE` mode it will return nothing. Differently, it could be matched if we use `BOOLEAN MODE`.
title: Modify fulltext search into boolean mode
project: SIKD
participants: @samudra-ajri @azophy

Modify fulltext search into boolean mode

---

src/app/GraphQL/Mutations/DocumentSignatureRejectMutator.php

- fix: add reject status to document after reject esign
- https://app.clickup.com/t/2kpm3tb
title: fix: add reject status to document after reject esign
project: SIKD
participants: @indraprasetya154 @samudra-ajri @fajarhikmal214 @azophy

fix: add reject status to document after reject esign

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- [feat: un-delete draft file after last people signed the document](https://github.com/jabardigitalservice/office-services/pull/454/commits/231caccdd18a1cc224fcb171f314d17c24f3df72)
- draft file will be deleted after registered document (new feature)
- https://app.clickup.com/t/2nfy848
title: feat: un-delete draft file after last people signed the document
project: SIKD
participants: @indraprasetya154 @samudra-ajri @azophy @fajarhikmal214

feat: un-delete draft file after last people signed the document

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- feat: change schema forward document to uk/tu after registered document on website
- forward to UK/TU will be forwarded after registered document (new feature)
- https://app.clickup.com/t/2nfyvvq
title:feat: change schema forward document to uk/tu after registered document on website
project: SIKD
participants: @indraprasetya154 @azophy @samudra-ajri @fajarhikmal214

feat: change schema forward document to uk/tu after registered document on website

---

src/app/Http/Traits/KafkaTrait.php

Modify method from `withMessage` to `withBodyKey`.
title: Modify the kafka message sending method
project: SIKD

Modify the kafka message sending method

---

src/app/Http/Traits/InboxFilterTrait.php

This modification will return no filter inboxes for user that have no role.
title: Modify inbox condition for no role users
project: SIKD
participants: @samudra-ajr

Modify inbox condition for no role users

---

src/app/Http/Controllers/V1/ListLoggedUsers.php
src/app/Http/Controllers/V1/LoggedUserCheckController.php
src/config/personalaccesstoken.php
src/routes/api.php

- This api tells if a user have ever logged in sidebar mobile or not
- The checking proccess uses the user `idNumber` (NIK/NIP)
- Because it is sperated from GraphQL service but still need a security, then a basic auth on the request  header is implemented
title: Add has logged user checker end point
project: SIKD
participants: @samudra-ajri @indraprasetya154  @fajarhikmal214 @azophy

Add has logged user checker end point

---

src/app/Http/Controllers/V1/SignaturedDocumentDownloadController.php
src/routes/api.php

- Add signatured document file download api. This api is needed beacuse graphQL can not handle file download service.
- Download file from url.
- Add log activity: download signatured letter.
title: Add download signatured document file service
project: SIKD
participants: @samudra-ajri @indraprasetya154 @fajarhikmal214  @wanzismail

Add download signatured document file service

---

src/app/Http/Traits/InboxFilterTrait.php
src/app/Models/InboxReceiver.php
src/graphql/inboxReceiver.graphql

The inboxes list will be filtered by the sender departments ids.
Task: https://app.clickup.com/t/307a1tu
```
inboxes(
first: 20
filter: {
scope: INTERNAL
receiverTypes: ""
statuses: ""
senderDepts: "3"
}
)
```
title: Add inbox filter by the sender depts ids
project: SIKD

Add inbox filter by the sender depts ids

---

src/app/Http/Traits/InboxFilterTrait.php

The previous filter is based on 'From_Id' field. Otherwise, it should use the 'createdBy' field from the inbox detail.
Task: https://app.clickup.com/t/307a1tu
title: Modify sender depts inbox filter
project: SIKD

Modify sender depts inbox filter

---

src/graphql/documentSignatureSent.graphql

- feat: add status queue at query document detail
* WAITING
* PROCESS
* DONE
* FAILED
````
{
documentSignatureSentMultiple(
documentSignatureSentIds: "XXX, ZZZ"
) {
id
status
progressQueue
}
}
````
title: feat: add status queue at query document detail
project: SIKD

feat: add status queue at query document detail

---

src/app/Http/Traits/InboxFilterTrait.php
src/graphql/inbox.graphql

- add opd sender id and name attribute to iInbox type
- modify filter by OPD to check if the sender is null
title: Modify filter by OPD
project: SIKD

Modify filter by OPD

---

src/app/Models/Rolecode.php

This checking regards to the query that already implemented on this [filter](https://github.com/jabardigitalservice/office-services/blob/development/src/app/Models/DocumentSignatureSent.php).
title: fix: add 'next' atribute checking
project: SIKD
participants: @samudra-ajri @azophy @indraprasetya154 @fajarhikmal214

fix: add 'next' atribute checking

---

src/app/Enums/InboxFileTypeEnum.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Models/Draft.php
src/app/Models/InboxFile.php
src/graphql/draft.graphql
src/graphql/inboxFile.graphql

- fix: invalid response document file if user used upload file (attachment) on drafting module
- attachments attribute can be multiple files
````
{
draft(draftId: "XXX", groupId: "XXX") {
id
draftId
draftDetail {
file
attachments {
url
}
}
}
}
````
https://app.clickup.com/t/3bn9t1c
title: fix: invalid response document file if user used upload file (attachment) on drafting module

fix: invalid response document file if user used upload file (attachment) on drafting module
