jabardigitalservice/office-services

src/app/Enums/DraftProcessTypeEnum.php
src/app/Models/Draft.php
src/app/Models/InboxReceiver.php
src/graphql/draft.graphql
src/graphql/inboxReceiver.graphql
src/graphql/schema.graphql

- Add draft into inbox receiver
```
{
inboxes(
first: 50
filter: {
forwarded: "0"
receiverTypes: "to_draft_keluar, to_draft_notadinas, to_draft_edaran, to_draft_sprint, to_draft_intruksi_gub, to_draft_sket, to_draft_super_tugas, to_draft_pengumuman, to_draft_surat_izin, to_draft_rekomendasi"
}
) {
pageInfo {
total
}
edges {
node {
inboxId
fromId
toId
isEndForward
sender {
role {
id
}
name
avatar {
url
}
}
date
draftDetail {
id
date
receiverAs
number
letterNumber
about
moreAbout
location
address
folder
}
}
}
}
}
```
__
title: Add drafts functionality
project: SIKD

Add drafts functionality

---

src/app/GraphQL/Types/DocumentSignatureSentType.php

Change validation from status success only to all status for allowing signature document
https://github.com/jabardigitalservice/office-services/pull/107#issue-1054471696
title: Merubah pengecekan status validasi tte dari status success ke semua status user tte sebelumnya (parent)
project: SIKD

Change validation from status success to all status

---

src/graphql/draft.graphql

- Add `draftStatus` that retrivied from `konsep` on 'InboxReceiverCorrection table'
- This attribute identify the draft status whether still on drafting `draftStataus=1` or already signed `draftStataus=0`
- Remove `DraftFilterInput` as no used yet
__
title: Add draft status attribute
project: SIKD

Add draft status attribute

---

src/app/Models/InboxReceiver.php

- Modify the inbox query to be using function query
title: Bugfix inbox history query
project: SIKD

Bugfix inbox history query

---

src/app/GraphQL/Queries/InboxQuery.php

Modify the inbox unread counter query to specify the 'TU' role.
__
title: Modify inbox unread counter query
project: SIKD

Modify inbox unread counter query

---

src/app/Models/InboxReceiver.php

##Overview
Add `copy()` method to keep the time consistent.
__
title: Modify inbox receiver 'ReceiveDate' setter
project: SIKD

Modify inbox receiver 'ReceiveDate' setter

---

src/app/Enums/FcmNotificationActionTypeEnum.php
src/app/Http/Controllers/V1/SendNotificationController.php
src/app/Http/Traits/SendNotificationTrait.php

- Add drafts action type
- Add drafts notification setup
- Modify inbox receiver notification setup
- Modify `setNotificationAttribute()` method
- On `setNotificationAttribute()` the `notification` parameter changed into `request`
__
title: Add draft notification
project: SIKD

Add draft notification

---

src/app/Models/InboxReceiverCorrection.php

Add `personalAccessToken` relation into inbox receiver correction table.
__
title: Add personalAccessToken relation
project: SIKD

Add personalAccessToken relation.

---

src/app/Http/Traits/SendNotificationTrait.php

- Add different message attribute for drafts actions (`DRAFT_REVIEW`, `DRAFT_DETAIL`)
- This modification for the client (mobile) purpose
__
title: Modify notification attributes
project: SIKD

Modify notification attributes

---

src/app/Http/Traits/SendNotificationTrait.php

Add action attribute into draft notification.
__
title: Add cction attribute into draft notification
project: SIKD

Add action attribute into draft notification

---

src/app/Models/InboxReceiverCorrection.php

- Add `ReceiverAs != to_koreksi` draft objective filter
- Remove `to_koreksi` type from receiverAs review status filter
- The draft with `to_koreksi` label should not be shown on the list
__
title: Modify draft review filter
project: SIKD

Modify draft review filter

---

src/app/Enums/InboxReceiverScopeType.php
src/app/GraphQL/Queries/InboxQuery.php
src/graphql/inbox.graphql

- Add unread disposition counter
__
title: Add unread disposition counter
project: SIKD

Add unread disposition counter

---

src/app/Console/Kernel.php
src/app/Exceptions/Handler.php
src/app/GraphQL/Queries/DocumentSignatureQuery.php
src/app/GraphQL/Queries/InboxQuery.php
src/app/GraphQL/Types/DocumentSignatureType.php
src/app/GraphQL/Types/InboxFileType.php
src/app/Http/Traits/SendNotificationTrait.php
src/app/Models/DocumentSignatureSent.php
src/app/Models/InboxReceiver.php
src/app/Models/InboxReceiverCorrection.php
src/app/Models/People.php
src/app/Models/PersonalAccessToken.php
src/composer.json
src/composer.lock
src/config/cache.php
src/config/database.php
src/config/filesystems.php
src/config/lighthouse.php
src/config/sanctum.php
src/config/session.php
src/tests/CreatesApplication.php
src/tests/Feature/ExampleTest.php
src/tests/Unit/ExampleTest.php

Clean code
__
title: Add unread disposition counter
project: SIKD

Clean code

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/InboxMutator.php
src/app/Models/InboxReceiver.php

Clean code
__
title: Codeclimate maintenability
project: SIKD

Codeclimate maintenability

---

src/app/GraphQL/Queries/InboxQuery.php
src/composer.lock
src/graphql/inbox.graphql

Add unread document signature request counter
```
{
inboxUnreadCount{
signature
}
}
```
__
title: Add unread document signature request counter
project: SIKD

Add unread document signature request counter

---

src/app/GraphQL/Queries/InboxQuery.php
src/graphql/inbox.graphql

Add unread draft counter.
```
{
inboxUnreadCount{
draft
}
}
```
__
title: Add unread draft counter
project: SIKD

Add unread draft counter

---

src/app/GraphQL/Queries/InboxQuery.php

- Modify the query, to check is the data on the `InboxReceiverCorretcion` table also listed on `konsep_naskah` table. 
__
title: Bugfix unread draft counter
project: SIKD

Bugfix unread draft counter

---

docker/docker-config/php.ini

- Adjust PHP memory limit
- title: fixing error limit untuk preview pdf detail konsep naskah
- project: SIKD
- participants: @indraprasetya154 @samudra-ajri @rizkyrmsyah @ayocodingit @rindibudiaramdhan

Adjust PHP memory limit

---

src/app/Models/DocumentSignature.php

- Adjust folder URL document signature with data existing condition
- title: Menyesuaikan folder URL dokumen yang perlu ditandatangani sesuai data dan kondisi di existing
- project: SIKD
- participants: @indraprasetya154 @samudra-ajri

Adjust folder URL document signature with data existing condition

---

src/app/Models/DocumentSignature.php

- Change file_exists to get_header on url document signature
- title: Merubah kondisi pengecekan folder URL dokumen yang perlu ditandatangani
- project: SIKD
- participants: @indraprasetya154 @samudra-ajri

Change file_exists to get_header on url document signature

---

src/app/Models/DocumentSignature.php

- Modify get header index checking string
- title: Modify get header index checking string
- project: SIKD
- participants: @indraprasetya154 @samudra-ajri

Modify get header index checking string

---

src/app/GraphQL/Queries/InboxQuery.php
src/config/constants.php

- Modify unread counter based on the custom people position.
- This custom position can be seen on https://whimsical.com/mapping-role-Q3xrkMrbko47vvncATe5cy
__
title: Modify unread counter based on peoplePosition
project: SIKD

Modify unread counter based on peoplePosition

---

src/app/GraphQL/Queries/InboxQuery.php

This modification due to the latest db migration on https://github.com/jabardigitalservice/office-services/pull/149.
title: Modify unread signature request counter.

Modify unread signature request counter

---

src/app/GraphQL/Mutations/InboxReceiverCorrectionMutator.php

- Add action notification for returning draft to the drafter
- Add `draftData` as a reusable parameter
__
title: Add returning draft notification

Add returning draft notification

---

src/app/Enums/InboxFilterTypeEnum.php
src/app/Enums/ListTypeEnum.php
src/app/Http/Traits/InboxFilterTrait.php
src/app/Models/InboxReceiver.php
src/app/Models/InboxReceiverCorrection.php
src/app/Models/People.php

- Refactor inbox receiver list filter
- Refactor inbox receiver correction list filter
- Add `InboxFilterTrait` to avoid duplicate codes between inbox-receiver and inbox-receiver-correction filters
- Refactor people list filter
- These modifications have purpose to reduce the code smells and duplicate issues
__
title: Clean code the filtering features

Clean code the filtering features

---

src/app/Http/Controllers/V1/DocumentDraftPdfController.php
src/app/Http/Traits/DraftTrait.php
src/app/Models/Draft.php
src/resources/views/pdf/layouts/attachment/attachment.blade.php
src/resources/views/pdf/layouts/attachment/header.blade.php
src/resources/views/pdf/layouts/master.blade.php
src/resources/views/pdf/layouts/signature.blade.php
src/resources/views/pdf/nota_dinas.blade.php
src/resources/views/pdf/surat_dinas.blade.php

- Refactoring template
- Rename template `outboxsuratdinas` to `surat_dinas`
- Add template `nota_dinas`
- This refactoring based on analytic on `surat dinas` & `nota dinas` template, so there's still a possibility to change the logic on the blade template
title: Merubah base template konsep naskah pdf untuk penyesuaian template nota dinas & surat dinas
project: SIKD

Enhance signature template from draft

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Models/Draft.php
src/graphql/draft.graphql

- Add file attribute on `draft` model
- Check draft is signed or not for `getDraftFileAttribute`
title: Menambahkan file attribute pada response konsep naskah
project: SIKD

Add file attribute on draft

---

src/app/GraphQL/Queries/InboxQuery.php

- This signature request counter modification due to the latest db migration on #149.
- Modify inbox regional counter
__
title: Modify unread draft signature request counter
project: SIKD

Modify unread draft signature request counter

---

src/app/Http/Traits/InboxFilterTrait.php

Modify the typo of the inbox filter by folder type.
__
title: Bugfix inbox filter by folder
project: SIKD

Bugfix inbox filter by folder

---

src/app/GraphQL/Mutations/InboxReceiverCorrectionMutator.php
src/app/Http/Traits/InboxFilterTrait.php

- Modify the filter by forward status condition
- Modify the notification wording
__
title: Modify the notification wording
project: SIKD

Modify the notification wording

---

src/resources/views/pdf/layouts/signature.blade.php
src/resources/views/pdf/nota_dinas.blade.php
src/resources/views/pdf/surat_dinas.blade.php

- Adjust template data & style with existing pdf
title: Memperbaiki template data & style existing konsep naskah pdf
project: SIKD

Adjust template data & style with existing pdf

---

src/app/GraphQL/Mutations/InboxReceiverCorrectionMutator.php

Modify the correction notification title
__
title: Modify the notification wording
project: SIKD

Modify the correction notification title

---

src/app/GraphQL/Mutations/InboxReceiverCorrectionMutator.php

Modify the correction notification title.
__
title: Modify the notification wording
project: SIKD

Bugfix the notification title

---

src/app/Http/Traits/DraftTrait.php
src/resources/views/pdf/layouts/attachment/header.blade.php
src/resources/views/pdf/layouts/signature.blade.php

- Fix date on attachment and signature reviewer role
title: Fix date on attachment and signature reviewer role
project: SIKD

Fix date on attachment and signature reviewer role

---

src/app/GraphQL/Queries/InboxQuery.php
src/app/Models/DocumentSignatureSent.php

- Modify the document signature sent filter query
- Modify the document signature unread counter
title: Modify signature filter and the counter
project: SIKD

Modify signature filter and the counter

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Models/Inbox.php

- Add draft forward to UK/TU after signed draft document
- Change status to SENT after signed document forward to UK/TU
title: Add draft forward to UK/TU after signed draft document
project: SIKD

Add draft forward to uk/tu

---

src/app/Http/Traits/DraftTrait.php
src/resources/views/pdf/nota_dinas.blade.php
src/resources/views/pdf/surat_dinas.blade.php

- Change query for getting carbon copy people position name
- Change query from Role to People by RoleId
title: Add first data on inbox receiver correction for draft timeline
project: SIKD

Change query for getting carbon copy people position name

---

src/app/Models/DocumentSignatureSent.php

- Modify relation by people id on `documentSignatureSentRead`
- Add where `people_id` = `auth user people id` on `documentSignatureSentRead` relation
title: Modify relation by people id on documentSignatureSentRead
project: SIKD

Modify relation by people id on documentSignatureSentRead

---

src/app/Http/Middleware/LogUserActivity.php
src/app/Http/Traits/LogUserActivityTrait.php
src/app/Models/LogUserActivity.php
src/config/lighthouse.php
src/database/migrations/2022_01_04_043355_create_log_user_activities_table.php

- Create log activity query/mutation
- Add middleware for handle create log activity
- Modify config/lighthouse.php to add custom middleware
- Add trait for handle web service (soon)
title: Create log activity query/mutation
project: SIKD

Create log activity query/mutation

---

src/app/Models/InboxCorrection.php
src/app/Models/InboxReceiverCorrection.php
src/graphql/inboxCorrection.graphql
src/graphql/inboxReceiverCorrection.graphql

- Add draft correction options from `inbox_koreksi` table
title: Add correction options
project: SIKD

Add correction options

---

src/app/GraphQL/Mutations/InboxMutator.php
src/app/GraphQL/Mutations/InboxReceiverCorrectionMutator.php

Modify notifications wordings
title: Modify notifications wordings
project: SIKD

Modify notifications wordings

---

src/app/Http/Traits/DraftTrait.php
src/resources/views/pdf/nota_dinas.blade.php
src/resources/views/pdf/surat_dinas.blade.php

- Change query for getting a list carbon copy
title: Change query for getting a list carbon copy
project: SIKD

Change query for getting a list carbon copy

---

src/app/GraphQL/Queries/DraftQuery.php

- Fix query for getting list draft timeline
title: Fix query for getting list draft timeline
project: SIKD

Fix query for getting list draft timeline

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/InboxMutator.php

Modify the notification  wordings of document signature request.
title: Modify signature request notifications wordings
project: SIKD

Modify signature request notifications wordings

---

src/app/Http/Controllers/V1/LogUserActivityController.php
src/app/Http/Traits/LogUserActivityTrait.php
src/resources/views/pdf/nota_dinas.blade.php
src/routes/api.php

- Create an endpoint for log user activity web existing
- Create invoke controller for handle request from web existing
- Add routes UserLogActivity
- Modify UserLogActivityTrait
title: Create an endpoint for log user activity web existing
project: SIKD

Create an endpoint for log user activity web existing

---

src/app/Models/InboxReceiverCorrection.php

- Modify the draft `SIGN_REQUEST` type query filter
- Modify the draft `REVIEW` type query filter
title: Modify the draft filters
project: SIKD

Modify the draft filters

---

src/app/Models/Draft.php

- Modify the draft get document file attribute
title: Modify get draft document file attribute
project: SIKD

Modify get draft document file attribute

---

src/app/GraphQL/Types/InboxReceiverCorrectionType.php
src/graphql/inboxReceiverCorrection.graphql

- Modify the isActioned attribute
- Add isActioned graphQl types
- Add isReturned attribute
title: Add isActioned graphQL types
project: SIKD

Add isActioned graphQL types

---

src/resources/views/pdf/layouts/master.blade.php
src/resources/views/pdf/nota_dinas.blade.php

- Modify template `notadinas` header & table size
title: Modify template `notadinas` header & table size
project: SIKD

Modify template notadinas header & table size

---

src/resources/views/pdf/layouts/attachment/header.blade.php
src/resources/views/pdf/nota_dinas.blade.php

- Fix date condition on header attachment at notadinas template pdf
title: Fix date condition on header attachment at notadinas template pdf
project: SIKD

Fix date condition on header attachment at notadinas template pdf

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php

- After the signed draft, the document with 'nota dinas' will be forwarded to Receiver People Ids and TU People Ids
title: Enhance list user forwarded people id on notadinas after signed the draft
project: SIKD

Enhance list user forwarded people id on notadinas after signed the draft

---

src/app/Enums/InboxReceiverCorrectionTypeEnum.php
src/app/GraphQL/Types/InboxReceiverCorrectionType.php
src/graphql/inboxReceiverCorrection.graphql

- Sender draft is the latest people interact with the user
- Base on the database existing schema, this enhancement will be slow down the query (at first time request) 
title: Enhance - Sender draft is latest people interact with the user
project: SIKD

Enhance - Sender draft is latest people interact with the user

---

src/app/Http/Middleware/LogUserActivity.php
src/app/Http/Traits/DraftTrait.php
src/app/Http/Traits/InboxFilterTrait.php
src/app/Http/Traits/LogUserActivityTrait.php
src/app/Http/Traits/SendNotificationTrait.php
src/app/Http/Traits/SignatureTrait.php

- Change user log activity query mapping
- Add doc comment for traits
title: Change user log activity query mapping
project: SIKD

Change user log activity query mapping

---

src/app/Enums/PeopleProposedTypeEnum.php
src/app/Models/People.php
src/graphql/people.graphql

This feature has purpose to filter the people list for the letter numbering.
title: Add numbering people list filter
project: SIKD

Add numbering people list filter

---

src/app/GraphQL/Mutations/InboxMutator.php

- Add `NUMBERING_UK` and `NUMBERING_TU` forward types
title: Add numbering forward feature
project: SIKD

Add numbering forward feature

---

src/app/Http/Controllers/V1/DocumentDraftPdfController.php
src/app/Http/Traits/DraftTrait.php
src/app/Models/Draft.php
src/resources/views/pdf/layouts/master.blade.php
src/resources/views/pdf/layouts/signature.blade.php
src/resources/views/pdf/surat_perintah.blade.php

- Create pdf template for regional letter instruction draft
- Set custom paper (F4) for regional letter instruction draft
title: Create pdf template for regional letter instruction draft
project: SIKD

Create pdf template for regional letter instruction draft

---

.github/workflows/release-staging.yml

- Modify github workflow script deploy to swarm
title: Modify github workflow script deploy to swarm
project: SIKD
participants: @indraprasetya154 @feriahmad @samudra-ajri

Modify github workflow script deploy to swarm

---

src/app/Models/InboxReceiverCorrection.php
src/graphql/inboxReceiverCorrection.graphql

- Enhance: Add receiver as a label on inbox receiver correction
title: Enhance: Add receiver as a label on inbox receiver correction
project: SIKD

Enhance: Add receiver as label on inbox receiver correction

---

src/app/Http/Traits/InboxFilterTrait.php
src/graphql/inboxReceiver.graphql

Add inbox list filter by followed-up status.
title: Add followed up status filter
project: SIKD

Add followed up status filter

---

src/app/Models/People.php

Add `DRAFT_FORWARD` people list which has the same behaviour as the FORWARD people list
proposed type.
title: Add DRAFT_FORWARD people list
project: SIKD

Add DRAFT_FORWARD people list

---

src/app/GraphQL/Mutations/InboxMutator.php

Add forwarding draft notification feature
title: Add forwarding draft notification
project: SIKD

Add forwarding draft notification

---

src/app/Http/Controllers/V1/LogUserActivityController.php
src/app/Http/Middleware/LogUserActivity.php
src/app/Http/Traits/LogUserActivityTrait.php

- Refactor log user activity format
title: Enhance: Refactor log user activity format
project: SIKD

Refactor log user activity

---

src/app/Http/Traits/InboxFilterTrait.php
src/app/Models/Draft.php

- Modify condition on outbox folder filter
- Remove HTML tag on about draft
title: Modify condition on outbox folder filter & about the draft
project: SIKD
participants: @indraprasetya154 @samudra-ajri @ayocodingit @sandisunandar99 @rizkyrmsyah

Modify data on outbox

---

src/app/Models/People.php

Modify the people list filter for showing the TU involved.
title: Modify people list TU filter
project: SIKD

Modify people list TU filter

---

src/app/GraphQL/Types/InboxReceiverCorrectionType.php

Modify sender signature request functionality.
title: Modify sender signature request
project: SIKD

Modify sender signature request

---

src/app/Http/Traits/InboxFilterTrait.php
src/app/Models/InboxReceiver.php

Modify the followed-up status filtering functionality
title: Modify the followed-up status filtering
project: SIKD

Modify the followed-up status filtering.

---

src/app/GraphQL/Mutations/InboxMutator.php
src/app/Models/People.php

- Modify the people list filtering functionality
- Add is a leader checking
title: Modify the people list
project: SIKD

Modify people list

---

src/app/GraphQL/Mutations/InboxMutator.php

- Add a default inbox forwarded receiver
- This receiver is a user department's UK
title: Add a default inbox forwarded receiver
project: SIKD

Add a default inbox forwarded receiver

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Models/Draft.php
src/resources/views/pdf/layouts/attachment/header.blade.php
src/resources/views/pdf/surat_dinas.blade.php
src/resources/views/pdf/surat_perintah.blade.php

- Fix template layout pdf draft position on next page
title: Fix template layout pdf draft position on next page
project: SIKD

Fix template layout pdf draft position on next page

---

src/app/Http/Traits/LogUserActivityTrait.php
src/composer.json
src/composer.lock
src/database/migrations/2022_01_28_084945_alter_log_user_activities_add_action.php

- Adjust table log and modify handle log activity
title: Adjust table log and modify handle log activity
project: SIKD
participants: @indraprasetya154 @ayocodingit @azophy  @rizkyrmsyah @rindibudiaramdhan @sandisunandar99 @rachadiannovansyah

Adjust table log and modify handle log activity

---

src/app/Http/Traits/DraftTrait.php

- Adjustment draft QRCode value with web existing page
- https://app.clickup.com/t/25du9u2
title: Adjustment draft QRCode value with web existing page
project: SIKD
participants: @indraprasetya154 @sandisunandar99 @ayocodingit

Adjustment draft QRCode value with web existing page

---

src/app/Enums/InboxReceiverCorrectionTypeEnum.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Bugfix validate the signature draft document
title: Bugfix validate the signature document
project: SIKD
participants: @indraprasetya154 @samudra-ajri @ayocodingit @rizkyrmsyah

Bugfix validate the signature draft document

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Models/Draft.php
src/resources/views/pdf/layouts/attachment/header.blade.php

- Change name file signed draft pdf
- Change attachment date default value
title: Fix template & name file pdf signed
project: SIKD
participants: @indraprasetya154 @samudra-ajri @rindibudiaramdhan

Fix template & name file pdf signed

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Models/Draft.php

- Change document file name attribute on draft model
title: Change document file name attribute on draft model
project: SIKD
participants: @indraprasetya154 @rizkyrmsyah @rachadiannovansyah @ayocodingit @samudra-ajri

Change document file name attribute on draft model

---

src/app/GraphQL/Mutations/InboxMutator.php

This function should change the `TindakLanjut` status only.
title: Modify endForward functionality
project: SIKD

Modify endForward functionality

---

src/app/Models/People.php
src/config/constants.php

- Modify the people positions constant
- Add specific people list for the governor uk numbering filter
title: Modify numbering poeple list
project: SIKD

Modify numbering poeple list

---

src/app/Models/Draft.php

- Change space with underscore on naming draft pdf file
title: Change space with underscore on naming draft pdf file
project: SIKD

Change space with underscore on naming draft pdf file

---

src/app/GraphQL/Mutations/InboxReceiverCorrectionMutator.php

Modify the body using html strip to clean the text
title: Clean the notification body
project: SIKD

Clean the notification body

---

src/app/Http/Controllers/V1/SendNotificationController.php

- Add html strip to clean the notification body
title: Modify the notif body to use html strip
project: SIKD

Modify the notif body to use html strip

---

src/app/Http/Traits/InboxFilterTrait.php

##Overview
This modification will determine that the letter from the Governor or the Vice Governor should be included on the `INTERNAL` scope, even they are from the different department from the login user.
title: Modify the inbox scope filter
project: SIKD

Modify the inbox scope filter

---

src/app/Http/Controllers/V1/SendNotificationController.php

##Overview
Notification will do nothing if the sender and the receiver have the same id.
title: Modify the notification condition
project: SIKD

Modify the notification condition

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Http/Traits/DraftTrait.php
src/app/Models/Draft.php
src/resources/views/pdf/layouts/signature.blade.php
src/resources/views/pdf/surat_perintah.blade.php

- Fix invalid template pdf & data `nota dinas` signature
title: Fix invalid template pdf & data `nota dinas` signature
project: SIKD

Bugfix signature nota dinas

---

src/app/Http/Controllers/V1/SendNotificationController.php

Regards to the web app, this condition should be implemented directly to the web.
title: Modify the notif condition
project: SIKD

Modify the notif condition

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Http/Traits/DraftTrait.php
src/app/Http/Traits/SignatureTrait.php

- Change validation on checking header pdf is exist
- [Change 200 with Response::HTTP_OK](https://github.com/jabardigitalservice/office-services/pull/232/commits/dc34640f249c44a45f7f87b167e1582a1015a237)
title: Change validation on checking header pdf is exist
project: SIKD
participants: @indraprasetya154 @sandisunandar99 @rizkyrmsyah @ayocodingit

Change validation on checking header pdf is exist

---

src/app/Enums/PeopleRoleIdTypeEnum.php
src/app/Models/People.php

These modifications are:
- Modify the forward filter
- Modify the numberingTU filter
**Modification on forward filter**
Distinguish the uk role from the other roles.
**Modification on the TU filter**
Will return its superior TU, if there has no direct TU.
title: Modify the people list forward filter
project: SIKD

Modify the people list forward filter

---

src/app/GraphQL/Mutations/InboxMutator.php

- Add the default receiver for the governor role
title: Modify the default draft receiver
project: SIKD

Modify the default draft receiver

---

src/app/GraphQL/Mutations/InboxMutator.php

Complete the content of the _review naskah_ notification.
title: Add review naskah notification content
project: SIKD

Add review naskah notification content

---

src/app/GraphQL/Mutations/InboxMutator.php

Add html tags strip for cleaning the notification body.
title: Add html tags strip for the notification body
project: SIKD

Add html tags strip for the notification body

---

src/app/GraphQL/Mutations/InboxMutator.php

For the meantime, the numbering notification will be deactivated according to this task: https://app.clickup.com/t/29q09ke
title: Modify the numbering notification
project: SIKD

Modify the numbering notification

---

src/app/Http/Traits/InboxFilterTrait.php
src/config/constants.php

- This modification is sperating the internal and regional scope query to classify the Governor Role.
- The Governor role will be classified as the Sekda group.
title: Modify the scope filter
project: SIKD

Modify the scope filter

---

src/app/Models/InboxReceiverCorrection.php

These modifications acording to the new label named `naskah telah direview`.
title: Modify inbox receiver correction filter
project: SIKD

Modify inbox receiver correction filter

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php

Add forward data on inbox receiver correction after signed draft document
title: Add forward data on inbox receiver correction after signed draft document
project: SIKD

Add forward data on inbox receiver correction after signed draft document

---

src/app/GraphQL/Mutations/InboxMutator.php

This modification mimics the website existing logic that updates the inbox `Status` and `TindakLanjut` fields.
title: Modify end forward functionality
project: SIKD

Modify end forward functionality

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/GraphQL/Queries/DraftHistoryQuery.php
src/app/Models/InboxReceiverCorrection.php
src/graphql/inboxReceiverCorrection.graphql
src/graphql/schema.graphql

Change response draft history query
Change response draft history query
project: SIKD

Change response draft history query

---

src/app/Models/InboxReceiverCorrection.php

Add `approvenaskah` label to the draft `SGINED` filter.
title: Add a label to the SIGNED draft filter
project: SIKD

Add a label to the SIGNED draft filter

---

src/app/Models/InboxReceiverCorrection.php

This modification is registering the review labels to the `SIGNED` filter.
title: Modify the signed labels filter
project: SIKD

Modify the signed labels filter.

---

src/graphql/schema.graphql

`outboxDrafts` is a feature that return the drafts which sent by the user
````
outboxDrafts(first: 20) {
edges {
node {
....
}
}
}
````
Add outboxDrafts feature
project: SIKD

Add outboxDrafts feature

---

src/graphql/schema.graphql

`outboxDocumentSignatureSents` is a feature that return the signature activities which sent by the user
````
outboxDocumentSignatureSents(first: 20) {
edges {
node {
....
}
}
}
````
title: Add document signature sents outbox
project: SIKD

Add document signature sents outbox

---

src/app/GraphQL/Queries/DraftHistoryQuery.php

- Change order by on draft history
title: Change order by on draft history
project: SIKD

Change order by on draft history

---

src/graphql/schema.graphql

- Add outbox draft searching feature 
- Add filtering
````
outboxDrafts(
first: 20
search: "...."
objective: OUT
filter: {
types: "...."
receiverTypes: "..." 
}
) {
edges {
node {
....
}
}
}
````
title: Add outbox draft filtering and searching
project: SIKD

Add outbox drafts filtering and searching

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/Models/DocumentSignature.php

- Set only first order document signature to add custom footer
- https://app.clickup.com/t/2nc67td
title: Set only first order document signature to add custom footer
project: SIKD

Set only first order document signature to add custom footer

---

src/app/Enums/ValidationDocumentTypeEnum.php
src/app/GraphQL/Queries/ValidationDocumentQuery.php
src/app/Models/DocumentSignature.php
src/graphql/inboxFile.graphql
src/graphql/schema.graphql
src/graphql/validation.graphql

- User should be able to validate documents from scan QRCode
* Main Task: https://app.clickup.com/t/2cr7xpu
* Sub Task (API): https://app.clickup.com/t/2d3rf7c
title: Feature validate documents from scan QRCode
project: SIKD

Feature validate documents from scan QRCode

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Queries/ValidationDocumentQuery.php

- User should be able to validate documents from input code
- Waiting phink migration success deploy
* Main Task: https://app.clickup.com/t/2d3q5gf
* Sub Task (API): https://app.clickup.com/t/2d3rfe8
title: Feature validate documents from input code
project: SIKD

Feature validate documents from input code

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Http/Controllers/V1/DocumentDraftPdfController.php
src/app/Http/Traits/DraftTrait.php
src/app/Models/Draft.php
src/resources/views/pdf/layouts/attachment/header.blade.php
src/resources/views/pdf/layouts/master.blade.php
src/resources/views/pdf/layouts/signature.blade.php
src/resources/views/pdf/surat_dinas.blade.php

- Add footer on draft document after esign
* https://app.clickup.com/t/2d3rj3c
* https://app.clickup.com/t/2d3rjnv
title: Add footer on draft document after esign
project: SIKD

Add footer on draft document after esign

---

src/app/Models/InboxReceiver.php
src/app/Models/InboxReceiverCorrection.php
src/graphql/inboxReceiver.graphql
src/graphql/inboxReceiverCorrection.graphql

- Add `actionLabel` attribute to `inbox_receiver` model
- Add `actionLabel` attribute to `inbox_receiver_koreksi` model
````
outboxDrafts(
...
) {
edges {
node {
actionLabel
}
}
}
````
title: Add action label attribute
project: SIKD

Add action label attribute

---

src/app/Enums/ActionLabelTypeEnum.php
src/app/GraphQL/Mutations/InboxReceiverCorrectionMutator.php

- Add action label type enum
- Add `REVIEWED` label to the returned back inbox
- Add `CORRECTION` label to the new inbox correction
title: Add action label: CORRECTION
project: SIKD

Add action label: CORRECTION

---

src/app/Enums/ActionLabelTypeEnum.php
src/app/GraphQL/Mutations/InboxMutator.php

- Add `FINISHED` label to the finished inbox
title: Add action label: FINISHED
project: SIKD

Add action label: FINISHED

---

src/app/Enums/ActionLabelTypeEnum.php
src/app/GraphQL/Mutations/InboxMutator.php

- Add `DISPOSITIONED` label to the dispositioned inbox
title: Add action label: DISPOSITIONED
project: SIKD

 Add action label: DISPOSITIONED

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/GraphQL/Queries/ValidationDocumentQuery.php

- Fix QRCode value on footer drafting
- Fix query for scan QRCode value
title: Fix validation draft document with QR
project: SIKD

Fix validation draft document with QR

---

src/app/GraphQL/Mutations/InboxMutator.php

- Add `REVIEWED` label to the forwarded inbox
title: Add action label: REVIEWED
project: SIKD

Add action label: REVIEWED

---

src/app/Enums/ActionLabelTypeEnum.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Add `APPROVED` label to the approved inbox
title: Add action label: APPROVED
project: SIKD

Add action label: APPROVED

---

src/app/Enums/ActionLabelTypeEnum.php
src/app/GraphQL/Mutations/InboxMutator.php

- Add `NUMBERING` label to the record that forwarded to the UK/TU
- Add `NUMBERING` label to a new reocrd that proposed to the UK/TU
title: Add action label: NUMBERING
project: SIKD

Add action label: NUMBERING

---

src/app/Enums/ActionLabelTypeEnum.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Add `SIGNED` label to the signed record
title: Add action label: SIGNED
project: SIKD

Add action label: SIGNED

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Http/Traits/DraftTrait.php
src/resources/views/pdf/layouts/master.blade.php

- Fix page size to F4
- Fix code value to uppercase
- Fix padding bottom page
title: Fix layout draft document
project: SIKD

Fix layout draft document

---

src/app/Enums/ActionLabelTypeEnum.php
src/app/GraphQL/Mutations/InboxMutator.php

Change label `DISPOSITIONED` to `DISPOSED`
title: Modify action label: DISPOSED
project: SIKD

Modify action label: DISPOSED

---

src/app/Enums/ActionLabelTypeEnum.php
src/app/Http/Traits/InboxFilterTrait.php
src/app/Models/InboxReceiver.php
src/app/Models/InboxReceiverCorrection.php
src/graphql/inboxReceiver.graphql
src/graphql/inboxReceiverCorrection.graphql

- Add `filterByActionLabel` trait function
- According to the `action_label` db field was implemented on 17 March '22, therefore, this filter also determines the filter at the date
title: Add action labels filter
project: SIKD

Add action labels filter

---

src/app/GraphQL/Queries/ValidationDocumentQuery.php

- Add validation with file name by qrcode value latest slug
- https://app.clickup.com/t/2cr7xpu
title: Add validation with file name by qrcode value latest slug
project: SIKD

Add validation with file name by qrcode value latest slug

---

src/app/GraphQL/Mutations/InboxMutator.php

This modification for the draft that already forwarded to be numbered.
title: Modify the NUMBERING label to REVIEWED
project: SIKD

Modify the NUMBERING label to REVIEWED

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Fix inbox receiver correction update status
title: Fix inbox receiver correction update status
project: SIKD

Fix inbox receiver correction update status

---

src/app/GraphQL/Types/InboxFileType.php
src/app/Models/InboxReceiver.php
src/graphql/inboxReceiver.graphql
src/graphql/schema.graphql

- [Fix signers empty](https://github.com/jabardigitalservice/office-services/commit/f6ce4a86f0ba4df6bc654cfa00bdcce9f25430e7)
- [Enhance inbox history query params](https://github.com/jabardigitalservice/office-services/commit/e03f2b28178f450b64df7506152a6abfd44f50b0)
* `inboxHistory` Query &rarr; cc @wanzismail 
* Move `inboxId` params to filter &rarr; inboxId
* Add `withAuthCheck` params &rarr; boolean value
* Set `true` on detail document &rarr; history
* Set `false` on validation document &rarr; history
Example:
````
{
inboxHistory(
filter: {
inboxId: "",
withAuthCheck: true
}
first: 10
) {
edges {
node {
sender {
name
}
receiver {
name
}
}
}
}
}
````
- https://app.clickup.com/t/2d3q9fk
title: Fix validation document response
project: SIKD

Fix validation document response

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- Fix forward document signature after signing a document
- https://app.clickup.com/t/2nc67v5
title: Fix forward document signature after signing a document
project: SIKD

Fix forward document signature after signing a document

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/Models/DocumentSignature.php

- Fix special character on the document file name for new file e-sign document
- https://app.clickup.com/t/2df5jjc
title: Fix special character on the document file name for new file e-sign document
project: SIKD

Fix special character on the document file name for new file e-sign document

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- Change validate footer with has footer
- https://gitlab.com/jdsteam/sikd-website/-/merge_requests/110
title: Change validate footer with has footer
project: SIKD

Change validate footer with has footer

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/GraphQL/Mutations/InboxMutator.php

Add default `action_label=REVIEW` for  the new records on the `inbox_receiver` and `inbox_receiver_koreksi` tables.
title: Add action label: REVIEW
project: SIKD

Add action label: REVIEW

---

src/app/Http/Traits/InboxFilterTrait.php

- This modification is according to the new action label implementation.
- This new implementation could be seen on this PR: https://github.com/jabardigitalservice/office-services/pull/282 
title: Modify the action label filter
project: SIKD

Modify the action label filter

---

src/graphql/documentSignature.graphql
src/graphql/documentSignatureType.graphql

Add document signature type graphql schema
title: Add document signature type gql schema
project: SIKD

Add document signature type gql schema

---

src/app/Models/DocumentSignatureSent.php

- Validate read params if null on list document signature
title: Validate read params if null on list document signature
project: SIKD

Validate read params if null on list document signature

---

src/app/GraphQL/Queries/InboxQuery.php

Modify the counter of the unread signatured inboxes
This modification accordings to the PR on: https://github.com/jabardigitalservice/office-services/pull/284
title: Modify unread signatured inbox counter
project: SIKD

Modify unread signatured inbox counter

---

src/app/Models/InboxReceiverCorrection.php

- Modify the objective out filter
title: Modify the objective filter: OUT
project: SIKD

Modify the objective filter: OUT

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- Add validation document signature update
title: Add validation document signature update
project: SIKD

Add validation document signature update

---

src/app/GraphQL/Queries/InboxQuery.php

Add some condition to modify the unread signature counter.
title: Modify the unread signature counter
project: SIKD

Modify the unread signature counter

---

src/app/Models/InboxReceiverCorrection.php
src/graphql/inboxReceiverCorrection.graphql

This function will filter the drafts by the `ReceiverAs` values.
title: Add filter by receiver label function
project: SIKD

Add filter by receiver label function

---

src/app/GraphQL/Types/InboxFileType.php
src/app/Models/InboxReceiver.php
src/graphql/inboxReceiver.graphql

- Fix validation document output signature & inbox history
title: Fix validation document output signature & inbox history
project: SIKD

Fix validation document output signature & inbox history

---

src/app/Http/Traits/DraftTrait.php
src/app/Models/Draft.php
src/resources/views/pdf/layouts/signature.blade.php
src/resources/views/pdf/surat_perintah.blade.php
src/resources/views/pdf/surat_rekomendasi.blade.php

- Create template letter recommendation pdf
- https://app.clickup.com/t/2g50rhx
- [letter-recommendation.pdf](https://github.com/jabardigitalservice/office-services/files/8367650/letter-recommendation.pdf)
title: Create template letter recommendation pdf
project: SIKD

Create template letter recommendation pdf

---

.github/workflows/release-staging.yml

- Add github workflow - remove unused key on deployment
title: Add github workflow - remove unused key on deployment
project: SIKD

Add github workflow - remove unused key on deployment

---

src/app/GraphQL/Mutations/InboxMutator.php

`action_label=REVIEW` bill be implemented to the new forwarded draft record
title: Add REVIEW label to the new forwarded draft
project: SIKD
participants: @samudra-ajri @indraprasetya154 @sandisunandar99

Add REVIEW label to the new forwarded draft

---

src/resources/views/pdf/layouts/signature.blade.php
src/resources/views/pdf/surat_rekomendasi.blade.php

- Adjustment letter recommendation pdf template
- https://app.clickup.com/t/2g50rhx
title: Adjustment letter recommendation pdf template
project: SIKD

Adjustment letter recommendation pdf template

---

src/app/GraphQL/Queries/InboxQuery.php
src/graphql/inbox.graphql

- Add the unread counter for forwarded inboxes
- Modify the regional counter as the accumulation counters of forward and disposition
title: Add unread forwarded inbox counter feature
project: SIKD

Add unread forwarded inbox counter feature

---

src/app/Models/InboxReceiverCorrection.php

This modification is added the 'meneruskan' label into the review filter
title: Modify the outbox drafts' receiver label filter
project: SIKD

Modify the outbox drafts' receiver label filter

---

src/resources/views/pdf/layouts/signature.blade.php

- Adjustment padding signature section
title: Adjustment padding signature section
project: SIKD

Adjustment padding signature section

---

src/app/Models/DocumentSignature.php
src/app/Models/Draft.php
src/graphql/documentSignature.graphql

- New format on renaming document esign
- https://app.clickup.com/t/2j9qrp1
title: New format on renaming document esign
project: SIKD

New format on renaming document esign

---

src/app/GraphQL/Types/DocumentSignatureSentType.php

- Modify read flag on document signature sent
- https://app.clickup.com/t/2jn15d9
title: Modify read flag on document signature sent
project: SIKD

Modify read flag on document signature sent

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- Add update file data on has footer true
title: Add update file data on has footer true
project: SIKD
participants: @indraprasetya154 @samudra-ajri @sandisunandar99 @rindibudiaramdhan @ayocodingit

Add update file data on has footer true

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Fix failed passphrase didn't logged
title: Fix failed passphrase didn't logged
project: SIKD

Fix failed passphrase didn't logged

---

src/app/Models/DocumentSignatureForward.php
src/graphql/documentSignatureForward.graphql
src/graphql/schema.graphql

- Add filtering by its read and distributed status
- Add searching the list by its file name
title: Add eksternal drafts filters and search
project: SIKD

Add eksternal drafts filters and search

---

src/app/Enums/StatusReadTypeEnum.php
src/app/GraphQL/Queries/ExternalDraftQuery.php
src/app/Models/DocumentSignatureForward.php
src/graphql/schema.graphql

- Add the `detail` function and the gql schema
- Add status read type enum
title: Add external draft detail feature
project: SIKD

Add external draft detail feature

---

src/app/Enums/ActionLabelTypeEnum.php
src/app/GraphQL/Mutations/DraftNumberMutator.php
src/graphql/inboxReceiverCorrection.graphql
src/graphql/schema.graphql

- Feature draft add a letter number
- https://app.clickup.com/t/2juw91j
````
mutation {
draftNumber(
input: {
draftId: "1"
number: "12345"
receiverId: "1"
}
) {
id
...
}
}
````
title: Feature draft add a letter number
project: SIKD

Feature draft add a letter number

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- Bugfix replace name document esign
title: Bugfix replace name document esign
project: SIKD

Bugfix replace name document esign

---

src/app/Models/DocumentSignatureSent.php
src/graphql/documentSignatureSent.graphql

This modification is adding advanced relation called `with` and its directive.
title: Modify the document signature sent relation
project: SIKD

Modify the document signature sent relation

---

src/app/GraphQL/Types/DocumentSignatureType.php
src/app/Models/DocumentSignature.php

- Add self sign history on validation document
- https://gitlab.com/jdsteam/sikd-website/-/merge_requests/151
title: Add self sign history on validation document
project: SIKD

Add self sign history on validation document

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

Hotfix name document esign
Reference form this PR :
- https://github.com/jabardigitalservice/office-services/pull/323

Hotfix name document esign

---

.github/workflows/release-production.yml

Clear space for the key on github action
title: Add clear space for key
project: SIKD

Add clear space for key

---

src/app/Models/Draft.php
src/graphql/schema.graphql

This list is a special drafts list for TU/UK roles
The client (mobile) could use this query
```
{
internalDrafts(
first: 20
isArchiver: true
){
pageInfo{
total
}
edges{
node{
id
about
folder
letterNumber
draftStatus
}
}
}
}
```
title: Add internal drafts list for TU/UK
project: SIKD

Add internal drafts list for UK/TU

---

src/app/Enums/DeptRoleCodeTypeEnum.php
src/app/Enums/PeopleRoleIdTypeEnum.php
src/app/Models/People.php
src/config/constants.php

This modification is to advance the list by user group positions.
title: Modify the people list proposed to be dispositioned
project: SIKD
participants: @indraprasetya154 @yohang88 @feriahmad @samudra-ajri

Modify the people list proposed to be dispositioned

---

src/app/Enums/PeopleGroupTypeEnum.php
src/app/Models/People.php

This modification will show no UK and TU on the disposition list.
title: Modify the proposed-to diposition list
project: SIKD

Modify the proposed-to diposition list

---

src/app/Models/People.php

- This modification will remove root user from the list
- On the governor list will show the group 3 users with the position 1 and 4
title: Modify the disposition proposed list
project: SIKD

Modify the disposition proposed list

---

src/app/Models/People.php

This modification will not show the secretary superior role.
title: Modify secretary disposition proposed list
project: SIKD

Modify secretary disposition proposed list

---

src/app/GraphQL/Mutations/InboxReceiverCorrectionMutator.php

Fix to update the approver of the origin draft when the draft is returning back.
title: Bugfix draft returning functionality
project: SIKD

Bugfix draft returning functionality

---

src/app/Models/DocumentSignatureForward.php
src/graphql/documentSignatureForward.graphql

Add filter by types for external drafts list.
title: Add external drafts filter by types
project: SIKD

Add external drafts filter by types

---

src/app/Models/People.php

This modification will make the UKSETDA role as the exception.
title: Modify the default forward list
project: SIKD

Modify the default forward list

---

src/app/Enums/InboxTypeEnum.php
src/app/Models/InboxReceiver.php

- Enhance receiver as label attribute for inbox history
- https://app.clickup.com/t/25cwf58
title: Add document signature distribute at document signature history
project: SIKD

Enhance receiver as label attribute for inbox history

---

src/app/Models/People.php
src/config/constants.php

This feature will show the people list that can be dispositioned by group 2 users except vice governor and SETDA.
title: Add group 2 leader disposition proposed list
project: SIKD

Add group 2 leader disposition proposed list

---

src/app/GraphQL/Queries/DocumentSignatureHistoryQuery.php

- Add condition when user self sign and self forward on document signature history
- https://app.clickup.com/t/2jfbvq2?comment=756869153
title: Add condition when user self sign and self forward on document signature history
project: SIKD

Add condition when user self sign and self forward on document signature history

---

src/app/GraphQL/Types/DocumentSignatureType.php
src/app/Models/DocumentSignature.php

- Bugfix document e-sign recreate file and verify response status
- https://app.clickup.com/t/27q51az
title: Bugfix document e-sign recreate file and verify response status
project: SIKD

Bugfix document e-sign recreate file and verify response status

---

src/app/GraphQL/Types/DocumentSignatureType.php
src/app/GraphQL/Types/InboxFileType.php

- Fix validation document if return 500 from the third party
title: Fix validation document if return 500 from the third party
project: SIKD

Fix validation document if return 500 from third party

---

src/app/GraphQL/Queries/DocumentSignatureHistoryQuery.php

- Add missing model DocumentSignature

Add missing model

---

src/app/Models/People.php
src/config/constants.php

- Add positions group 5 constant
- Add disposition people proposed list for positions group 5
title: Add disposition people proposed list for group 5
project: SIKD

Add disposition people proposed list for group 5

---

docker/Dockerfile

Modify newrelic version to be updated.
title: Update new relic version
project: SIKD

Update new relic version

---

src/app/GraphQL/Queries/InboxQuery.php
src/graphql/inbox.graphql

- This feature will count the disposition and non disposition letters
- In consequence, the disposition counter will be deprecated and replaced by registration counter
The cilent (mobile) should change all of `disposition` counter into `registration` counter.
title: Add registration letters unread counter
project: SIKD

Add registration letters unread counter

---

src/config/constants.php

Add some positions into group 5 constant.
title: Add more group 5 positions
project: SIKD

Add more group 5 positions

---

src/app/Models/People.php
src/graphql/schema.graphql

This feature will search the people by name or position.
Sample query for client:
```
{
peopleList(
first: 100
search: "..."
filter:{
proposedTo: DISPOSITION
}
){
...
}
}
```
title: Add people search feature
project: SIKD

Add people search feature

---

src/app/Models/Inbox.php
src/graphql/draft.graphql
src/graphql/inbox.graphql

- Add classified on inbox and draft
title: Add classified on inbox and draft
project: SIKD

Add classified on inbox and draft

---

src/app/Models/People.php

This condition will show no leaders when the user is a sub dept chief.
title: Add sub department disposition proposed condition
project: SIKD

Add sub department disposition proposed condition

---

src/app/Models/People.php

- Modify the disposition proposed list for position group 5
- This modification will have the same behaviour with the group 3
title: Modify the group 5 proposed dispotition list
project: SIKD

Modify the group 5 proposed dispotition list

---

src/app/Models/People.php

Modify the proposed list for group position 5 to get all the list user on their departments.
title: Modify the group 5 disposition proposed list
project: SIKD

Modify the group 5 disposition proposed list

---

src/app/Enums/InboxTypeEnum.php
src/app/GraphQL/Mutations/DistributeDocumentMutator.php
src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Queries/DocumentSignatureHistoryQuery.php
src/app/GraphQL/Types/DocumentSignatureType.php
src/app/GraphQL/Types/InboxFileType.php
src/app/Models/DocumentSignature.php
src/app/Models/InboxReceiver.php

- [Add registration letters unread counter](https://github.com/jabardigitalservice/office-services/commit/ff699e6cc69cedc0ad5a6e499079dbdc16977bf6)
- [Add disposition people proposed list for group 5](https://github.com/jabardigitalservice/office-services/commit/f357fa102fbe13f8558f190f4f6be74f2b7e26a6)
- [Modify newrelic version to be updated](https://github.com/jabardigitalservice/office-services/commit/56116d54a0bb3a52e0e96fd6d2f857cf4e081ba4)
- [Add people search feature](https://github.com/jabardigitalservice/office-services/commit/a0650cfffb6d130f04c0163ec65a46976e49083e)
- [Add classified on inbox and draft](https://github.com/jabardigitalservice/office-services/commit/7036bb31b9ade6194c93c7e80f64dc584cf38030)

Up to Production - 28 April 2022

---

src/app/Models/People.php

Modify the proposed list for group position 5 to get all the list user on their departments.
title: Bugfix disposition proposed list for group role 5
project: SIKD

Bugfix disposition proposed list for group role 5

---

src/app/Models/People.php

Remove the chief disposition proposed filter.
title: Modify the chief department disposition proposed list
project: SIKD

Modify the chief department disposition proposed list

---

src/app/Models/People.php
src/config/constants.php

Add filter function that shows the disposition proposed list for the vice directors.
title: Add vice director disposition proposed list
project: SIKD

Add vice director disposition proposed list

---

src/app/GraphQL/Queries/InboxQuery.php

Add function that specifies the receiverAs list for registration (semua naskah) letter type.
title: Add registration data 'receiver as' group list
project: SIKD

Add registration data 'receiver as' group list

---

src/app/GraphQL/Queries/InboxQuery.php

Add source filter condition for the counter.
title: Modify registration inbox unread counter
project: SIKD

Modify registration inbox unread counter

---

src/app/Http/Traits/InboxFilterTrait.php

Add condition to hide the forwarded letter from the UK, if the list is 'semua naskah' (count of the receiver types == registration type).
title: Modify the filter by receiver types
project: SIKD

Modify the filter by receiver types

---

src/app/GraphQL/Queries/InboxQuery.php
src/app/Http/Traits/InboxFilterTrait.php

- [ Modify the filter by receiver types](https://github.com/jabardigitalservice/office-services/commit/5315598a3f745d7c2edde514f7c4e3c40b939dac)
title: Up to Production - 12 May 2022 (2)
project: SIKD

Up to Production - 12 May 2022 (2)

---

src/app/GraphQL/Queries/InboxQuery.php

Modify the unread registration letter counter to remove the unused code.
title: Modify the unread registration letter counter
project: SIKD

Modify the unread registration letter counter

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Http/Traits/SignatureTrait.php

- Clean code esign code
- Add throw if error on connect third party
title: Add throw if error on connect third party
project: SIKD

Add throw if error on connect third party

---

src/app/GraphQL/Queries/InboxQuery.php
src/graphql/inbox.graphql

Add unread counter for carboncopy letter (tembusan surat).
title: Add carboncopy unread counter
project: SIKD

Add carboncopy unread counter

---

src/app/Enums/PeopleIsActiveEnum.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Set people is active on forward draft to inbox receiver
title: Set people is active on forward draft to inbox receiver
project: SIKD

Set people is active on forward draft to inbox receiver

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/graphql/classification.graphql
src/graphql/draft.graphql

- Add classification and role code on the draft response
- Include fix minor invalid parameter method
title: Add classification and role code on draft response
project: SIKD

Add classification and role code on draft response

---

src/app/GraphQL/Queries/InboxQuery.php
src/app/Http/Traits/InboxFilterTrait.php

Add more receiver types for registration (semua naskah) list.
title: AAdd more receiver types for registration list
project: SIKD

Add more receiver types for registration list

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Fix invalid forward data after esign draft
title: Fix invalid forward data after esign draft
project: SIKD

Fix invalid forward data after esign draft

---

src/app/Enums/PeopleProposedTypeEnum.php
src/app/Models/People.php
src/graphql/people.graphql

This will show the user's direct inferiors (bawahan) people list.
title: Add direct disposition people list
project: SIKD

Add direct disposition people list

---

src/app/Http/Traits/InboxFilterTrait.php

This query will fiter the list that non disposition types.
The client (mobile) should change its query.
From:
```
{
inboxes(
first: 10
search: ""
filter: {
receiverTypes: "cc1, to, to_undangan, to_sprint, to_notadinas, to_reply, to_usul, to_forward, to_keluar, to_nadin, to_konsep, to_memo, to_rekomendasi, to_surat_izin_keluar, to_pengumuman, to_super_tugas_keluar, to_edaran"
}
) {
...
{
}
```
To this:
```
{
inboxes(
first: 10
search: ""
filter: {
receiverTypes: "cc1, nondisposition"
}
) {
...
{
}
```
title: Add nondisposition query filter
project: SIKD

Add nondisposition query filter

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Fix condition column type draft checking
title: Fix condition column type draft checking
project: SIKD

Fix condition column type draft checking

---

src/app/GraphQL/Mutations/DraftNumberMutator.php

- Fix group id on submit draft letter number
title: Fix group id on submit draft letter number
project: SIKD

Fix group id on submit draft letter number

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Update array of people id on draft esign notadinas
- https://app.clickup.com/t/2a1q8fh?comment=810877329
title: Update array of people id on draft esign notadinas for notification
project: SIKD

Update array of people id on draft esign notadinas

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Fix typo message notification
title: Fix typo message notification
project: SIKD
participants: @indraprasetya154 @ayocodingit @imamdev93 @firmanhxc

Fix typo message notification

---

src/app/Http/Traits/InboxFilterTrait.php

This modification defines the new term of REGIONAL and INTERNAL filters:
- REGIONAL is letters that sent by UK
- INTERNAL is letters that not sent by UK
title: Modify the scope filtering
project: SIKD

Modify the scope filtering

---

docker/Dockerfile

- Fix newrelic source/
- Tested on non M1 laptop 
title: Fix newrelic source
project: SIKD
participants: @indraprasetya154 @samudra-ajri @yohang88

Fix newrelic source

---

src/app/Http/Traits/InboxFilterTrait.php
src/app/Models/InboxReceiver.php

These modifications consist of:
- combine receievertype and scope filtering
- distinct the forward with another actions
title: Modify to advance the inbox scope filtering
project: SIKD

Modify to advance the inbox scope filtering

---

src/app/Http/Traits/InboxFilterTrait.php
src/app/Models/InboxReceiver.php

Reverts jabardigitalservice/office-services#401 because the query is too heavy.
title: Revert "Modify to advance the inbox scope filtering"
project: SIKD

Revert "Modify to advance the inbox scope filtering"

---

src/app/Http/Traits/InboxFilterTrait.php

Add internal scope filter for Governor
title: Add governor internal scope filter
project: SIKD

Add governor internal scope filter

---

src/graphql/inbox.graphql

Add inbox `fromScope` attribute as `AsalNaskah` 
title: Add inbox fromScope attribute
project: SIKD

Add inbox fromScope attribute

---

src/graphql/schema.graphql

Create `orderBy` from client side.
title: Add inboxes orderBy directive
project: SIKD

Add inboxes orderBy directive

---

src/app/GraphQL/Types/DocumentSignatureType.php
src/app/GraphQL/Types/InboxFileType.php

- Remove validation by NIP on list validation document
- This code remove because data from BSRE not include NIP anymore
title: Remove validation by NIP on list validation document
project: SIKD

Remove validation by NIP on list validation document

---

src/app/Models/InboxReceiver.php

- [Add condition checking by to id on inbox history](https://github.com/jabardigitalservice/office-services/commit/fd2a90fec9f830f309308486c0e1e13929f382b7)
title: Add condition checking by to id on inbox history
project: SIKD

Add condition checking by to id on inbox history

---

src/app/Enums/InboxReceiverScopeType.php
src/app/Http/Traits/InboxFilterTrait.php
src/graphql/inboxReceiver.graphql

This filter will return letters that registered from the external West Java gov.
title: Add external scope filter
project: SIKD

Add external scope filter

---

src/graphql/schema.graphql

The list can be ordered by the client.
title: Add signature letter dynamic sorting
project: SIKD

Add signature letter dynamic sorting

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Change url qrcode esign document
- Waiting verifiy page ready before merge this PR
- Change add footer branch development on caprover
title: Change url qrcode esign document
project: SIKD

Change url qrcode esign document

---

src/app/Models/InboxReceiver.php

- [Enhance label of receiver as at inbox response](https://github.com/jabardigitalservice/office-services/commit/307cc450016ac21ee406801a2687f48d626c070d)
- https://app.clickup.com/t/25cwf58?comment=804690660
title: Enhance label of receiver as at inbox response
project: SIKD

Enhance label of receiver as at inbox response

---

src/app/Models/DocumentSignatureSent.php
src/graphql/documentSignatureSent.graphql

This filter will return the list based on the types.
title: Add outbox signature types filter
project: SIKD

Add outbox signature types filter

---

src/app/Models/DocumentSignatureSent.php

- Add next filter list on model document signature sent
- https://app.clickup.com/t/2d8fzax
title: Add next filter list on model document signature sent
project: SIKD

Add next filter list on model document signature sent

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- Set param on forward receiver after esign by drafter role
- https://app.clickup.com/t/2dtxv8x
title: Set param on forward receiver after esign by drafter role
project: SIKD
participants: @indraprasetya154 @samudra-ajri @fajarhikmal214 @ayocodingit @sandisunandar99 @imamdev93

Set param on forward receiver after esign by drafter role

---

src/app/Http/Traits/InboxFilterTrait.php

- This modification is combining the filter with `receiverAs` type
- Simplify the external scope to use whereRelation function
title: Modify scope filtering
project: SIKD

Combine scope receiver filter

---

src/app/Http/Traits/InboxFilterTrait.php

This modification is replacing whereHas with whereRelation function.
title: Modify Non Disposition query
project: SIKD

Modify Non Disposition query

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php

- Change error response reason esign with BSrE body error
title: Change error response reason esign with BSrE body error
project: SIKD

Change error response reason esign with BSrE body error

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- Fix forward document people list after esign
title: Fix forward document people list after esign
project: SIKD

Fix forward document people list after esign

---

src/app/GraphQL/Queries/ValidationDocumentQuery.php

- Change validation document flow after url qrcode already change
- https://app.clickup.com/t/2egm878
- Detail pattern URL QRCode https://app.clickup.com/t/2egm878?comment=864719553
- Pattern of URL QRCode already change from real path file to abstraction path
- So, it will change the logic of the scan QRcode method for validation document
title: Change validation document flow following new URL QRCode pattern
project: SIKD
participants: @indraprasetya154 @fajarhikmal214 @azophy @samudra-ajri

Change validation document flow following new URL QRCode pattern

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- [Enhance find TU account by sender data](https://github.com/jabardigitalservice/office-services/commit/42e74ee5b4ea35ef8f2f17256959d3a97e1afb83)
- https://app.clickup.com/t/2dtxv8x
title: Enhance find TU account by sender data and anomaly data
project: SIKD

Enhance find TU account by sender data and anomaly data

---

src/app/Enums/FcmNotificationListTypeEnum.php
src/app/Http/Controllers/V1/SendNotificationController.php

- This list attribute is needed by the mobile client to determine the specific action.
- The list types are:
- DISPOSITION
- INBOX_REGIONAL
- INBOX_INTERNAL
- DRAFT_OUTSIDE
- DRAFT_INSIDE
- CARBONCOPY
- SIGNATURE
title: Add list notification attributes
project: SIKD

Add list notification attributes

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DocumentSignatureRejectMutator.php
src/app/GraphQL/Mutations/DraftNumberMutator.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/GraphQL/Mutations/InboxMutator.php
src/app/GraphQL/Mutations/InboxReceiverCorrectionMutator.php
src/app/Http/Traits/DistributeToInboxReceiverTrait.php
src/app/Http/Traits/SendNotificationTrait.php

Adding list attribute to the specific notification types:
- DISPOSITION
- INBOX_INTERNAL
- INBOX_REGIONAL
- DRAFT_OUTSIDE
- DRAFT_INSIDE
- SIGNATURE
title: Add notification list attributes
project: SIKD
participants: @indraprasetya154 @fajarhikmal214

Add notification list attributes

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- After esign, the document should be able to forward into UK/TU drafter account
- In this case, the document should be able to forward info UK **Wakil Gubernur** account
- But mobile get invalid message error, detail on related task section below
- Fix find UK account at governor role for forwarding document
- Fix try-catch for handler transfer document into website existing storage
- Add DB transaction for handling update data transaction
- https://app.clickup.com/t/2dtxv8x?comment=846814068
title: Fix find UK account at governor role for forwarding document
project: SIKD
participants: @indraprasetya154 @rachadiannovansyah @fajarhikmal214 @samudra-ajri

Fix find UK account at governor role for forwarding document

---

src/app/Enums/FcmNotificationListTypeEnum.php
src/app/Enums/InboxOriginTypeEnum.php
src/app/GraphQL/Mutations/InboxMutator.php

These notifications are:
- INBOX_INTERNAL_GUB: letters from internal West Java Goverenment
- INBOX_EXTERNAL_GUB: letters from external West Java Goverenment
title: Add notification lists types for the Governor role
project: SIKD

Add notification lists types for the Governor role

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- Adjust transfer file for unlink data after document esign
- https://gitlab.com/jdsteam/sikd-website/-/merge_requests/299
title: Adjust transfer file for unlink data after document esign
project: SIKD

Adjust transfer file for unlink data after document esign

---

src/app/Models/DocumentSignature.php
src/graphql/documentSignature.graphql

- Set new url file for document esign (draft label file and esign file)
- https://app.clickup.com/t/2h6e7ye
title: Set new url file for document esign (draft label file and esign file)
project: SIKD

Set new url file for document esign (draft label file and esign file)

---

src/app/Models/DocumentSignature.php

- Enhance url public attribute for old data
- https://app.clickup.com/t/2h6e7ye
title: Enhance url file document attribute for old data
project: SIKD

Enhance url file document attribute for old data

---

src/app/Http/Traits/SendNotificationTrait.php

This modification will return the complete request data from client.
title: Modify notifcation data
project: SIKD

Modify notifcation data

---

src/app/Models/InboxReceiver.php

- This mode will replace the `LIKE` searching method.
- This will perform better performance reagards to the `FULLTEXT` index type.
The index type replacement from `BTREE` into `FULLTEXT` is here: https://gitlab.com/jdsteam/sikd-website/-/merge_requests/303
title:  Add NATURAL LANGUAGE searching mode
project: SIKD

Add NATURAL LANGUAGE searching mode.

---

src/app/Http/Traits/InboxFilterTrait.php
src/app/Models/InboxReceiver.php

These modifications consist of:
- change `query like` according to the table indexing
- change the order of the filters ragards to the new indexing
New compound indexing: https://gitlab.com/jdsteam/sikd-website/-/merge_requests/307
title: Modify inbox filter for performance enhancement
project: SIKD

Modify inbox filter for performance enhancement

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Http/Traits/SignatureTrait.php

- enhance: message wording esign to bahasa
title: enhance: message wording esign to bahasa
project: SIKD
participants: @indraprasetya154 @samudra-ajri @fajarhikmal214 @azophy

enhance: message wording esign to bahasa

---

src/app/Models/Inbox.php
src/graphql/inbox.graphql

This attribute will return the path of the attachment file.
title: Add inbox attachment attribute
project: SIKD
participants: @samudra-ajri @fajarhikmal214

Add inbox attachment attribute

---

src/app/GraphQL/Mutations/DocumentSignatureRejectMutator.php

- This PR following changes on website logic
- https://gitlab.com/jdsteam/sikd-website/-/merge_requests/325/diffs#1e3e53b391da27f37515cb49feb1acab9f17d6f1_1811_1820
title: Change column date time of reject document esign
project: SIKD

Change column date time of reject document esign

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- enhance: change document status on last people esign list
title: enhance: change document status on last people esign list
project: SIKD
participants: @indraprasetya154 @azophy @samudra-ajri @fajarhikmal214

enhance: change document status on last people esign list

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DocumentSignatureRejectMutator.php

- [feat: change document status on reject document esign](https://github.com/jabardigitalservice/office-services/commit/326d989b02491fe7b6a6f6e47ec4ff6ca3a4b76f)
- [feat: change document status on last people list document esign](https://github.com/jabardigitalservice/office-services/commit/94862a34825a252f7c546cef1a67b2306c54568b)
https://github.com/jabardigitalservice/office-services/pull/449
https://github.com/jabardigitalservice/office-services/pull/450
Since we need to update to production on the specified feature, I create a new branch and move the change from `Reference PR` into this Pull Request, **please check `Reference PR` first**
title: Up to production - 12 July 2022 Mobile API
project: SIKD
participants: @indraprasetya154 @samudra-ajri @azophy @fajarhikmal214

Up to production - 12 July 2022

---

src/app/Models/InboxReceiver.php

- Change condition label of inbox receiver at history query
- https://app.clickup.com/t/2mdfkwp
title: Change condition label of inbox receiver at history query
project: SIKD

Change condition label of inbox receiver at history query

---

src/app/Models/InboxReceiver.php

- Change letter label to letter non disposition
- https://app.clickup.com/t/2mdfkwp
title: Change letter label to letter non disposition
project: SIKD

Change letter label to letter non disposition

---

src/app/GraphQL/Queries/DocumentSignatureHistoryQuery.php
src/graphql/documentSignatureSent.graphql

- enhance: change response of document forward following the registration document signature
- https://app.clickup.com/t/2pcet51
title: enhance: change response of document forward following the registration document signature
project: SIKD

enhance: change response of document forward following the registration document signature

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DocumentSignatureRejectMutator.php

This modificatin is adding `action` attribute to the notification.
https://app.clickup.com/t/2p6pcjw
title: Modify document signature mutator notification
project: SIKD

Modify document signature mutator notification

---

src/app/Http/Traits/KafkaTrait.php

This topic used `analytic_event`
title: Modify kafka topic
project: SIKD

Modify kafka topic

---

src/app/Http/Traits/KafkaTrait.php

Add log area for kafka publisher
title: Add log area for kafka publisher
project: SIKD

Add log area for kafka publisher

---

src/app/GraphQL/Mutations/AuthMutator.php
src/app/Http/Traits/KafkaTrait.php
src/config/kafka.php

- roleDesc attribute cant be read
Reverts jabardigitalservice/office-services#472

Revert "Add Kafka publish compression type configuration"

---

src/app/GraphQL/Mutations/AuthMutator.php
src/app/Http/Traits/KafkaTrait.php
src/app/Models/People.php
src/config/kafka.php

- Change kafka `withBodyKey` to `withMessage` method
- Add kafka compression config to be none
- Add log activity: login
- Hidden `PeoplePassword` attribute
- task: https://app.clickup.com/t/2h6ccdt
title: Modify kafka publish method
project: SIKD

Modify kafka publish method

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

This action need to be implemented on forwarding signed document.
- task: https://app.clickup.com/t/2tkk329
title: Add action notification attribute
project: SIKD
participants: @samudra-ajri @indraprasetya154 @azophy

Add action notification attribute

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/GraphQL/Queries/DraftQuery.php
src/app/GraphQL/Queries/ExternalDraftQuery.php
src/app/GraphQL/Queries/InboxQuery.php

- Add read_letter log activity
- Add rea_register_letter log activity
- task: https://app.clickup.com/t/2h6ccdt
title: Add log activity: read_letter
project: SIKD
participants: @samudra-ajri @azophy @fajarhikmal214

Add log activity: read_letter

---

src/app/GraphQL/Mutations/InboxMutator.php

- Add letter action (e.g. : Disposition, Forward, etc.) log
- task: https://app.clickup.com/t/2h6ccdt
title: Add log activity: letters action
project: SIKD
participants: @samudra-ajri @azophy @indraprasetya154 @fajarhikmal214

Add log activity: letters action

---

src/app/GraphQL/Mutations/DocumentSignatureRejectMutator.php

Add reject esign activity log
- task: https://app.clickup.com/t/2h6ccdt
title: Add log activity: reject_esign
project: SIKD

Add log activity: reject_esign

---

src/app/GraphQL/Mutations/AuthMutator.php
src/app/Http/Traits/InboxFilterTrait.php
src/app/Http/Traits/KafkaTrait.php
src/app/Models/People.php

This addition regards to the new policy that the `fungsional` role is erased.
title: Add optional chaining for user role
project: SIKD
participants: @samudra-ajr @indraprasetya154 @fajarhikmal214

Add optional role

---

src/app/GraphQL/Queries/DocumentSignatureQuery.php

- bugfix: handle objective params for old mobile app at document signature detail
- https://sentry.io/organizations/jabardigitalservice/issues/3502421966/?environment=production&project=5980429&query=is%3Aunresolved
title: bugfix: handle objective params for old mobile app at document signature detail
project: SIKD

bugfix: handle objective params for old mobile app at document signature detail

---

src/database/migrations/2022_08_19_091437_index_table_personal_access_tokens_add_index_tokenable_id.php

This index could be implemented for login process.
title: Add personal access tokens index table
project: SIKD

Add personal access tokens index table

---

src/app/Http/Traits/InboxFilterTrait.php
src/database/migrations/2022_08_19_091437_index_table_personal_access_tokens_add_index_tokenable_id.php

- Add personal access tokens table index
title: Up to Production - 22 Agustus 2022
project: SIKD

Up to Production - 22 Agustus 2022

---

src/app/Models/InboxReceiverCorrection.php

This modification will change the searching method from LIKE to FULLTEXT.
This modification regards to the fulltext index addtion on this detail: https://gitlab.com/jdsteam/sikd-website/-/merge_requests/462
title: Modify the drafts search method
project: SIKD

Modify the drafts search method

---

src/app/Models/InboxReceiverCorrection.php
src/database/migrations/2022_08_19_091437_index_table_personal_access_tokens_add_index_tokenable_id.php

- Implement composite indexing from the database
- [Modify the drafts search method](https://github.com/jabardigitalservice/office-services/commit/4914c4737493960ea61cc02be9a3052f2e5261d5)
title: Up to Production - 24 Agustus 2022 Mobile
project: SIKD

Up to production - 24 August 2022

---

src/app/Enums/BsreStatusTypeEnum.php
src/app/GraphQL/Mutations/DocumentSignatureMutator.php
src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Http/Traits/SignatureTrait.php

- enhance: message on checking NIK status
- https://gitlab.com/jdsteam/sikd-website/-/merge_requests/475
title: enhance: message on checking NIK status mobile
project: SIKD
participants: @indraprasetya154 @samudra-ajri @azophy @fajarhikmal214

enhance: message on checking NIK status

---

src/app/Http/Traits/KafkaTrait.php

Change timestamp from unix to ISO.
title: Hotfix: Modify log timestamp format
project: SIKD

Hotfix: Modify log timestamp format

---

src/app/Http/Controllers/V1/LoggedUserCheckController.php

This modification to difference the response beetwen: user not found (404) and user never logged in (412).
title: Modify the user never logged in status code
project: SIKD
participants: @samudra-ajri @azophy @indraprasetya154

Modify the user never logged in status code

---

src/app/GraphQL/Mutations/AuthMutator.php
src/app/Http/Traits/KafkaTrait.php
src/app/Models/Group.php
src/app/Models/People.php

- [enhance: kafka data refference session website](https://github.com/jabardigitalservice/office-services/commit/1646f080d3cc9ac76542d5d1c3f83b5b549de559)
title: Up to production - 31 August 2022 - set kafka data refference session website
project: SIKD

Up to production - 31 August 2022

---

src/app/Enums/KafkaStatusTypeEnum.php
src/app/GraphQL/Mutations/AuthMutator.php

- Add log activity: login invalid credentials
- Modify login succes log status
Issue request: https://github.com/jabardigitalservice/office-services/issues/511
title: Modify login logs
project: SIKD
participants: @samudra-ajri @indraprasetya154 @yohang88 @fajarhikmal214

Modify login logs

---

src/app/Enums/DocumentDownloadListTypeEnum.php
src/app/Http/Controllers/V1/DocumentDownloadController.php
src/app/Models/Draft.php

- Add feature to download draft document file
- Add download draft document log
- Task: https://app.clickup.com/t/2y87utj
title: Add downlaad draft document feature
project: SIKD
participants: @samudra-ajri @fajarhikmal214

Add downlaad draft document feature

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php

This modificatio to detail the log.
Task: https://app.clickup.com/t/2y87vr1
title: Modify log activity: esign_sign_draft
project: SIKD
participants: @samudra-ajri @fajarhikmal214 @indraprasetya154

Modify log activity: esign_sign_draft

---

src/app/Models/Inbox.php

This bugfix will handle the inbox that has no documentfile relation.
[Occured error report](https://sentry.io/organizations/jabardigitalservice/issues/3605163552/?environment=staging&project=5980429&query=is%3Aunresolved)
title: Bugfix document base url accessor not found
project: SIKD

Bugfix document base url accessor not found

---

src/app/GraphQL/Queries/DocumentSignatureQuery.php

Add kafka logging when read a document signature event.
https://app.clickup.com/t/2h6ccdt
title: Add log activity: Read Document Signature
project: SIKD
participants: @samudra-ajri @fajarhikmal214 @indraprasetya154

Add log activity: Read Document Signature

---

src/graphql/roleCode.graphql
src/graphql/schema.graphql

This feature will show the dapartments list.
- [Task](https://app.clickup.com/t/307a1tu)
- [Followed up comment](https://github.com/jabardigitalservice/office-services/pull/528#pullrequestreview-1119728880)
title: Add depertment list query
project: SIKD
participants: @samudra-ajri @fajarhikmal214

Add depertments list query

---

src/app/GraphQL/Mutations/InboxMutator.php
src/graphql/schema.graphql

This feature will change the inbox receiver status read manually.
Task: https://app.clickup.com/t/30cr5v3
title: Add modify letter status read feature
project: SIKD

Add modify letter status read feature

---

src/app/Http/Traits/InboxFilterTrait.php

- Add internal province scope filter
- This filter will replace the internal scope filter behaviour. 
- This addition ragards to the new beahaviour of the users inboxes list.
Task: https://app.clickup.com/t/307a0y5
title: Add internal province scope filter
project: SIKD
participants: @samudra-ajri @fajarhikmal214 @indraprasetya154

Add internal province scope filter

---

src/graphql/documentSignatureSent.graphql

This directive is added to provide the eagerload of doc signature sents.
Sentry report: https://sentry.io/organizations/jabardigitalservice/issues/3658205038/?project=5980429
title: Add document signature sents '@with' directive
project: SIKD

Add document signature sents '@with' directive

---

src/app/Http/Controllers/V1/DepartmentUnitController.php
src/app/Http/Controllers/V1/DocumentClassifiedController.php
src/app/Http/Controllers/V1/DocumentSignatureFileController.php
src/app/Http/Controllers/V1/DocumentTypeController.php
src/app/Http/Controllers/V1/EsignDocumentCheckStatusController.php
src/app/Http/Controllers/V1/EsignDocumentTypeController.php
src/app/Http/Controllers/V1/EsignSignerController.php
src/app/Models/DocumentSignature.php
src/routes/api.php

API list:
- GET /v1/units
- GET /v1/document-types
- GET /v1/document-classified
- GET /v1/esign/documents/types
- GET /v1/esign/signers
- GET /v1/esign/documents
NB:
- These apis is not implement the auth yet, hence the auth will use keycloack.
- Because the lack of resource, the `GET /v1/esign/documents` has a different body response with the api contract:
The contract:
```
{
"data": [
{
"id": "0001",
"status": "SUCCESS",
"file": "http:.../document/12345"
},
{
...
}
]
}
```
This api:
```
{
"data": [
{
"id": "0001",
"status_id": 1,
"status_name": "SUCCESS"
"file_url": "http:.../document/12345/file"
},
{
...
}
]
}
```
- API contract: https://s.id/SidebarAPIDocumentation
title: Add integrations apis
project: SIKD

Add integrations apis

---

src/app/Http/Controllers/V1/DepartmentUnitController.php
src/app/Http/Controllers/V1/DocumentClassifiedController.php
src/app/Http/Controllers/V1/DocumentSignatureFileController.php
src/app/Http/Controllers/V1/DocumentTypeController.php
src/app/Http/Controllers/V1/EsignDocumentCheckStatusController.php
src/app/Http/Controllers/V1/EsignDocumentTypeController.php
src/app/Http/Controllers/V1/EsignSignerController.php
src/app/Models/DocumentSignature.php
src/routes/api.php

The PR alredy at: https://github.com/jabardigitalservice/office-services/pull/547

Add integration lists api

---

src/app/Models/People.php

Modifies the SEKDA's disposition list like as the Governor's list.
Task: https://app.clickup.com/t/35jupch
title: bugfix: self notification invalid token data type
project: SIKD

Modify sekda disposition list

---

src/app/GraphQL/Mutations/DocumentSignatureMultipleMutator.php
src/app/Http/Traits/KafkaTrait.php
src/app/Http/Traits/SignDocumentSignatureTrait.php
src/app/Http/Traits/SignatureTrait.php
src/app/Jobs/ProcessMultipleEsignDocument.php

- feat: save header request at kafka
https://app.clickup.com/t/36fad30
title: feat: save header request at kafka
project: SIKD
participants: @indraprasetya154 @azophy @fajarhikmal214

feat: save header request at kafka

---

src/app/Http/Traits/KafkaTrait.php
src/app/Jobs/ProcessMultipleEsignDocument.php

- [fix: invalid set variable value for request data user multiple esign](https://github.com/jabardigitalservice/office-services/commit/78b153214345881b1a856fcc88586a6d255520e9)
https://app.clickup.com/t/36fad30
title: [fix: invalid set variable value for request data user multiple esign](https://github.com/jabardigitalservice/office-services/commit/78b153214345881b1a856fcc88586a6d255520e9)
project: SIKD
participants: @indraprasetya154 @azophy @fajarhikmal214 @samudra-ajri

fix: invalid set variable value for request data user multiple esign

---

src/app/GraphQL/Mutations/DocumentSignatureMutator.php

- fix: add header on single esign
https://app.clickup.com/t/36fad30
title: fix: add header on single esign
project: SIKD
participants: @indraprasetya154 @azophy @samudra-ajri @fajarhikmal214

fix: add header on single esign

---

src/app/Http/Traits/SignDocumentSignatureTrait.php

- fix: chore: esign multiple self notification
title: fix: chore: esign multiple self notification
project: SIKD

chore: esign multiple self notification

---

src/graphql/inboxReceiver.graphql

Modify the inbox disposition relation to use @belongsTo.
title: fix: roleback directive to the @belongsTo
project: SIKD

fix: roleback directive to the @belongsTo

---

src/graphql/inboxReceiver.graphql

Up to production - fix: roleback directive to the @belongsTo 
title: Up to production - fix: roleback directive to the @belongsTo 
project: SIKD
participants: @indraprasetya154 @azophy @samudra-ajri @fajarhikmal214

Up to production - fix: roleback directive to the @belongsTo 

---

src/app/Helpers/Helpers.php
src/app/Models/DocumentSignatureSent.php
src/config/constants.php
src/graphql/documentSignatureSent.graphql

- [feat: add flag from special sender user](https://github.com/jabardigitalservice/office-services/commit/e49b6f540236d52ffc8a0369716e6ed8a0b0c267)
- [fix: change validation with user logged in](https://github.com/jabardigitalservice/office-services/commit/17b9167e9c855e6293c4016668bac1fe6bf0f155)
https://app.clickup.com/t/38twp6c
title: Enhance add flag from special sender user
project: SIKD

Enhance add flag from special sender user

---

src/app/Models/DocumentSignatureSent.php
src/graphql/documentSignatureSent.graphql

This filter will list the TTE request based on the sender OPD.
Task: https://app.clickup.com/t/38twp9d
PR: https://github.com/jabardigitalservice/office-services/pull/575 (the OPD list)
title: Add TTE list filter by OPD
project: SIKD
participants: @samudra-ajri @azophy @indraprasetya154 @fajarhikmal214

Add TTE list filter by OPD

---

src/app/Enums/ListTypeEnum.php
src/app/Models/Rolecode.php
src/graphql/roleCode.graphql
src/graphql/schema.graphql

- This feature will filter OPD list based on letter types. 
- Letter types consisted by Inbox and Signature list.
Task: https://app.clickup.com/t/38twp9d
title: Modify filter by OPD
project: SIKD
participants: @samudra-ajri @azophy @indraprasetya154 @fajarhikmal214

Add OPD list filter by letter list type

---

src/app/Models/Rolecode.php

This query already run on local env. However, there is an issue while on staging.
It is probably caused by the uncorrect table name.
title: fix: modify the table name query
project: SIKD
participants: @samudra-ajri @fajarhikmal214 @indraprasetya154

fix: modify the table name query

---

src/app/Http/Traits/InboxFilterTrait.php

Modify the join table method into sub query.
This modification has purpose to flexible the OPD filter to be combined with another filters.
##Evidence
title: fix: ensure the OPD combination filter
project: SIKD
participants: @samudra-ajri @indraprasetya154 @azophy @fajarhikmal214

fix: ensure the OPD combination filter

---

.github/workflows/release-prod-jcloudv2.yml

- release production specific master branch to harbor | jcloud-v2
https://app.clickup.com/t/36n34uu
title: release production specific master branch harbor
project: SIKD
participants: @ftmfauzi @indraprasetya154 @samudra-ajri

release production specific master branch

---

src/app/Http/Traits/InboxFilterTrait.php

This addition filter will include the letters that `Pengirim` is internal.
title: fix: add 'Pengirim' checking condition
project: SIKD
participants: @samudra-ajri @azophy @fajarhikmal214 @indraprasetya154

fix: add 'Pengirim' checking condition

---

.github/workflows/release-prod-jcloudv2.yml

- Infra jabarcloud setup production ci/cd
https://app.clickup.com/t/370kjhe
title: Infra jabarcloud setup production ci/cd
participants: @indraprasetya154 @ftmfauzi

Infra jabarcloud setup production ci/cd

---

src/app/Http/Traits/SignInitDocumentSignatureTrait.php

- fix: invalid validation on already sign on self esign
https://app.clickup.com/t/38tvqzv
title: fix: invalid validation on already sign on self esign

fix: invalid validation on already sign on self esign

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Http/Traits/SignActionDocumentSignatureTrait.php
src/app/Http/Traits/SignNotificationDocumentSignatureTrait.php
src/app/Jobs/ProcessMultipleEsignDocument.php

- fix: esign worker error handle for website
https://app.clickup.com/t/38tvqzv
title: fix: esign worker error handle for website

fix: esign worker error handle for website

---

src/app/Http/Traits/InboxFilterTrait.php

- Add the condition where the AsalNaskah is null.
- Inbox which has null AsalNaskah will be provided on the result.
title: feat(filter-opd): include the null 'AsalNaskah'
project: sidebar
participants: @samudra-ajri @indraprasetya154 @fajarhikmal214 @azophy

feat(filter-opd): include the null 'AsalNaskah'

---

src/app/Models/MasterAnnouncement.php
src/graphql/masterAnnouncement.graphql
src/graphql/schema.graphql

- Added announcements query
````
query GetAnnouncement {
announcements(first: 100) {
edges {
node {
name
description
}
}
}
}
````
title: Added announcements query
participants: @anandarh @indraprasetya154 @samudra-ajri @fajarhikmal214

Added announcements query

---

src/app/GraphQL/Mutations/DraftSignatureMutator.php
src/app/Http/Traits/SignInitDocumentSignatureTrait.php

- enhance: remove check nik from do esign
title: enhance: remove check nik from do esign

enhance: remove check nik from do esign
